### ISSUE TITLE
Parsing issue with some specs

### ISSUE THREAD

**Issue by anshbansal** [spockframework/spock#109]
If I am using a closure with any groovy function in then spock is not able to parse it.

I am using `compile "org.gebish:geb-spock:0.9.0"` as my dependency in grails 2.2.4.

If I add semicolons in the Closure then it works otherwise it throws an exception. I have tried the code outside of spock in grails 2.2.4 and parsing exception does not occur. So this is issue with spock.

Below is example that reproduces the problem
```
import spock.lang.Specification

class AseemSpec extends Specification{


    def "abc"() {
        when:
        List dataPerMinute = []  //Should have been List of map

        then:
        dataPerMinute.any { Map it ->

            Date tmpTime = parse(it.time as String)

            int minute = tmpTime.toCalendar().get(Calendar.MINUTE)

            minute != 0
        }
    }

    Date parse(String it) {
        new Date()
    }
}
```

The error is
```
| Running 1 spock test... 1 of 1
--Output from abc--
--Output from abc--
| Failure:  abc(AseemSpec)
|  org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Spec expression: 1: expecting '}', found 'minute' @ line 1, column 125.
   lendar().get(Calendar.MINUTE) minute != 
                                 ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:106)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:148)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:359)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:142)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:108)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:236)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at grails.plugin.spock.test.GrailsSpecTestType.doRun(GrailsSpecTestType.groovy:73)
	at _GrailsTest_groovy.run_closure4(_GrailsTest_groovy:290)
	at _GrailsTest_groovy.run_closure2(_GrailsTest_groovy:248)
	at _GrailsTest_groovy.run_closure1_closure21(_GrailsTest_groovy:195)
	at _GrailsTest_groovy.run_closure1(_GrailsTest_groovy:184)
	at TestApp.run_closure1(TestApp.groovy:82)
| Completed 1 spock test, 1 failed in 28ms

```

**Comment by AndreasTu** [comment]
Closing old stale issue with Spock 1.x.
