### ISSUE TITLE
build fails with java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Kitke** [spockframework/spock#116]
./gradlew clean build results in 3 failed test. Exception thrown: 

```java
org.spockframework.smoke.FeatureFiltering > filter selected feature methods FAILED
    java.lang.IllegalArgumentException
        at groovy.util.ProxyGenerator.instantiateAggregate(ProxyGenerator.java:161)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:117)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:103)
        at org.spockframework.smoke.FeatureFiltering.filter selected feature methods(FeatureFiltering.groovy:33)

org.spockframework.smoke.FeatureFiltering > filtering all feature methods results in exception FAILED
    java.lang.IllegalArgumentException
        at groovy.util.ProxyGenerator.instantiateAggregate(ProxyGenerator.java:161)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:117)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:103)
        at org.spockframework.smoke.FeatureFiltering.filtering all feature methods results in exception(FeatureFiltering.groovy:54)

org.spockframework.smoke.FeatureFiltering > filtering across inheritance chain FAILED
    java.lang.IllegalArgumentException
        at groovy.util.ProxyGenerator.instantiateAggregate(ProxyGenerator.java:161)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:117)
        at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:103)
        at org.spockframework.smoke.FeatureFiltering.filtering across inheritance chain(FeatureFiltering.groovy:79)
```

OS Elementary OS 0.3 Freya (Ubuntu 14.04) x64
Java JDK 1.8.0_51
Gradle 2.5

**Comment by leonard84** [comment]
Could you also post the commit hash and the variant you are testing. 
It defaults to 2.0, could you also test `-Dvariant=2.4`

**Comment by Kitke** [comment]
@leonard84 Sure thing! Commit hash is '97fcd004b4208662144ab7450ac2bff9acc8e3e0' 
I've tried with default settings and the result was as described above. Building with '-DVariant=2.4' flag, as you've suggested, works fine.

**Comment by AndreasTu** [comment]
Closing old stale issue, regarding old now unsupported Groovy variant 2.0

**Comment by Vampire** [comment]
If anyone is interested, this was because the build was run with Java 8, but Groovy only properly supports Java 8 from 2.3 on, so running with Groovy 2.0 on Java 8 was the problem causing this. :-)
