### ISSUE TITLE
2.0-M3 : @Unroll should not be used in data-driven test without iteration

### ISSUE THREAD

**Issue by adbonnin** [spockframework/spock#1206]
# Issue description
`@Unroll` is used by default in data-driven test (with `where:` block) even if the variables are **not** an iteration.

The `where:` block is useful for separating the variables from the test logic even if there is no iteration.
In this case the `@Unroll` should not be applied by default (as mention in the [breaking change of the 2.0-M1](http://spockframework.org/spock/docs/2.0-M1/all_in_one.html#_breaking_changes)).

# How to reproduce
Create a test with a `where:` block without iterable variables.

_For example:_
```
def "my test" {
   expect:
   true

   where:
   a = "test"
}
```

# Additional Environment information

## IDE
IntelliJ 2019.3

### Apache Maven
```
<dependency>
   <groupId>org.spockframework</groupId>
   <artifactId>spock-core</artifactId>
   <version>2.0-M3-groovy-2.5</version>
   <scope>test</scope>
</dependency>
```

**Comment by Vampire** [comment]
How does that syntax provide more separation than
```groovy
def "my test" {
   given:
   def a = "test"

   expect:
   true
}
```
?

You can also use `@Rollup` if you want to prevent the unrolling for a specific feature or spec or disable the automatic unrolling through the spock configuration file.

**Comment by adbonnin** [comment]
@Vampire : I'm using the `given:` block to initialize values and parameters are placed in the `where:` block.

The `@Rollup` may be a solution but I have got a the following error when using it with IntelliJ :
````
java.lang.NoSuchMethodError: org.junit.platform.engine.support.hierarchical.Node$DynamicTestExecutor.execute(Lorg/junit/platform/engine/TestDescriptor;Lorg/junit/platform/engine/EngineExecutionListener;)Ljava/util/concurrent/Future;

	at org.spockframework.runtime.ParameterizedFeatureChildExecutor.execute(ParameterizedFeatureChildExecutor.java:58)
	at org.spockframework.runtime.PlatformParameterizedSpecRunner.runIterations(PlatformParameterizedSpecRunner.java:183)
	at org.spockframework.runtime.PlatformParameterizedSpecRunner.runParameterizedFeature(PlatformParameterizedSpecRunner.java:44)
	at org.spockframework.runtime.ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:35)
	at org.spockframework.runtime.ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:16)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:24)
	at org.spockframework.runtime.FeatureNode.lambda$around$0(FeatureNode.java:29)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:202)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:405)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:388)
	at org.spockframework.runtime.PlatformSpecRunner.runFeature(PlatformSpecRunner.java:195)
	at org.spockframework.runtime.FeatureNode.around(FeatureNode.java:29)
	at org.spockframework.runtime.FeatureNode.around(FeatureNode.java:7)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:24)
	at org.spockframework.runtime.SpecNode.lambda$around$0(SpecNode.java:61)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:62)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:405)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:388)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:56)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:61)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by Vampire** [comment]
You could sepearate your params and init with an `and` label like

```groovy
  def "my test"() {
    given:
    def a = "test"

    and:
    initialize()

    expect:
    true
  }
```

or even name the labels like
```groovy
def "my test"() {
  given: 'set parameters'
  def a = "test"

  and: 'initizalize values'
  initialize()

  expect:
  true
}
```

or even do the params before the `given` label like
```
def "my test"() {
  def a = "test"

  given:
  initialize()

  expect:
  true
}
```

Having them in the `where` block also needs less performance, as the `where` block adds a certain amount of complexity to the transformed code to be able to provide its services.

Regarding the exception when using `@Rollup`, this method was added in JUnit 5.7.0-M1 / JUnit Platform Engine 1.7.0-M1.
Spock 2.0-M3 depends on these versions.
It seems you somehow forced an older version being used where the method does not exist yet.

**Comment by adbonnin** [comment]
The third one should correspond because it is the most expressive. I'm already using the `and:` block to separate different initialization concern (services / library).
