### ISSUE TITLE
After execute method success,throw NullPointerException

### ISSUE THREAD

**Issue by adminSxs** [spockframework/spock#1293]
```springboot version: 2.2.0 release```
```spock version: 1.3-groovy-2.5```
Exception:
```
java.lang.NullPointerException: null
	at com.sun.proxy.$Proxy35.isEmpty(Unknown Source)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:104)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:75)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:110)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:75)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:98)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:92)
	at org.springframework.core.style.DefaultValueStyler.style(DefaultValueStyler.java:69)
	at org.springframework.core.style.DefaultToStringStyler.styleValue(DefaultToStringStyler.java:96)
	at org.springframework.core.style.DefaultToStringStyler.styleField(DefaultToStringStyler.java:83)
	at org.springframework.core.style.ToStringCreator.append(ToStringCreator.java:157)
	at org.springframework.test.context.support.DefaultTestContext.toString(DefaultTestContext.java:235)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener.beforeOrAfterTestMethod(AbstractDirtiesContextTestExecutionListener.java:107)
	at org.springframework.test.context.support.DirtiesContextTestExecutionListener.afterTestMethod(DirtiesContextTestExecutionListener.java:80)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:441)
	at org.spockframework.spring.SpringTestContextManager.afterTestMethod(SpringTestContextManager.java:64)
	at org.spockframework.spring.SpringInterceptor.interceptCleanupMethod(SpringInterceptor.java:67)
	at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:33)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:475)
	at org.spockframework.runtime.BaseSpecRunner.runCleanup(BaseSpecRunner.java:417)
	at org.spockframework.runtime.BaseSpecRunner.runCleanup(BaseSpecRunner.java:412)
	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:323)
	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:306)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:285)
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:275)
	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:266)
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:260)
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:243)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:235)
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by adminSxs** [comment]
i cannot find what's the problems

**Comment by Vampire** [comment]
The crystal ball is at the repair shop, can you provide a way how to reproduce the problem?
Maybe run through a debugger and set a breakpoint on `NullPointerException`s, or / and use a newer Java version that outputs more helpful information if you activate it like what actually was `null`.

**Comment by leonard84** [comment]
Hi, this question is better suited for [Stackoverflow](https://stackoverflow.com/questions/tagged/spock), I'm pretty sure the problem is not caused by Spock, but by something in your application context and interacting with Spring.

Before posting the same thing question, please read up on how to create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
