### ISSUE TITLE
Stub returning another stub in inline method definition fails with NPE

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock#1351]
## Describe the bug

See https://stackoverflow.com/q/68060743/1082681.

## To Reproduce

```java
package de.scrum_master.q68060743

import spock.lang.Specification

class UnpredictableStubInitialisationTest extends Specification {
  def "my failing test"() {
    given:
    var upload = Mock(Upload){
      waitForCompletion() >> { throw new InterruptedException() }
    }

    var transferManager = Mock(TransferManager) {
      upload(_,_,_) >> upload
    }

    when:
    var up = transferManager.upload(null, null, null)
    up.waitForCompletion()

    then:
    thrown(InterruptedException)
  }
  
  def "my working test"() {
    given:
    var upload = Mock(Upload) {
      waitForCompletion() >> { throw new InterruptedException() }
    }
    var transferManager = Mock(TransferManager)
    transferManager.upload(_,_,_) >> upload

    when:
    var up = transferManager.upload(null, null, null)
    up.waitForCompletion()

    then:
    thrown(InterruptedException)
  }
  
  static class Upload {
    String id
    void waitForCompletion() {
      println "Waiting for completion"
    }
  }

  static class TransferManager {
    Upload upload(String a, String b, String c) {
      println "Uploading"
      new Upload(id: a)
    }
  }
}
```

## Expected behavior

Both tests pass.

## Actual behavior

```text
Expected exception of type 'java.lang.InterruptedException', but got 'java.lang.NullPointerException'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at de.scrum_master.stackoverflow.q68060743.UnpredictableStubInitialisationTest.my failing test(UnpredictableStubInitialisationTest.groovy:21)
Caused by: java.lang.NullPointerException: Cannot invoke method waitForCompletion() on null object
	at de.scrum_master.stackoverflow.q68060743.UnpredictableStubInitialisationTest.my failing test(UnpredictableStubInitialisationTest.groovy:18)
```

The error is the same under Spock 1.3 on older Groovy and JDK versions, if you change `var` to the usual Groovy `def`.

# Environment:

Spock 2.0, Groovy 3.0.8

## Java/JDK

11.0.10

## Build tool version

Maven 3.6.3

## Operating System

Windows 10 Pro

## IDE

IntelliJ IDEA

**Comment by leonard84** [comment]
This is caused because you named the variable `upload` which is the same name as the method you want to call on `TransferManager`. 

```groovy
    var upload = Mock(Upload){
      waitForCompletion() >> { throw new InterruptedException() }
    }

    var transferManager = Mock(TransferManager) {
      upload(_,_,_) >> upload
    }
```
In this case the local variable has a higher precedence over the delegation of the closure, which is why things go awry.
I don't think there is much we can do on the Spock side as this how groovy works.

```groovy
def upload = new Upload()
    def transferManager = new TransferManager()
    transferManager.with {
      upload("a", "b", "c")
    }
```
will fail with `groovy.lang.MissingMethodException: No signature of method: Upload.call() is applicable for argument types: (String, String, String) values: [a, b, c]`

The easiest way to fix the example, is to rename the variable to something non-conflicting. Alternatively, you can prefix the stubbing with `it.` to make it unambiguous.

**Comment by kriegaex** [comment]
Sorry for the noise. I definitely overlooked the naming issue. Thanks for the great explanation. 🙂

**Comment by leonard84** [comment]
No worries, it could have been a bug and when you post something it is always with an MCVE so it is easy to debug in most cases.

**Comment by kriegaex** [comment]
Just in order to better document the problem and two possible workarounds for later reference:

```java
package de.scrum_master.stackoverflow.q68060743

import org.spockframework.runtime.WrongExceptionThrownError
import spock.lang.FailsWith
import spock.lang.Specification

class UnpredictableStubInitialisationTest extends Specification {
  @FailsWith(WrongExceptionThrownError)
  def "Upload mock has same name as stubbed method in TransferManager mock"() {
    given:
    def upload = Stub(Upload){
      waitForCompletion() >> { throw new InterruptedException() }
    }

    def transferManager = Stub(TransferManager) {
      upload(_,_,_) >> upload
    }

    when:
    def up = transferManager.upload(null, null, null)
    up.waitForCompletion()

    then:
    thrown(InterruptedException)
  }
  
  def "renamed Upload mock variable solves the problem"() {
    given:
    def uploadStub = Stub(Upload){
      waitForCompletion() >> { throw new InterruptedException() }
    }

    def transferManager = Stub(TransferManager) {
      upload(_,_,_) >> uploadStub
    }

    when:
    def up = transferManager.upload(null, null, null)
    up.waitForCompletion()

    then:
    thrown(InterruptedException)
  }

  def "not stubbing inline solves the problem"() {
    given:
    def upload = Stub(Upload) {
      waitForCompletion() >> { throw new InterruptedException() }
    }
    def transferManager = Stub(TransferManager)
    transferManager.upload(_,_,_) >> upload

    when:
    def up = transferManager.upload(null, null, null)
    up.waitForCompletion()

    then:
    thrown(InterruptedException)
  }
  
  static class Upload {
    String id
    void waitForCompletion() {
      println "Waiting for completion"
    }
  }

  static class TransferManager {
    Upload upload(String a, String b, String c) {
      println "Uploading"
      new Upload(id: a)
    }
  }
}
```
