### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.opentest4j.ValueWrapper org.opentest4j.ValueWrapper.create(java.lang.Object, java.lang.String)'

### ISSUE THREAD

**Issue by driversti** [spockframework/spock#1369]
### Describe the bug

I've faced a very strange issue trying to compare a not empty string with `null`.
Please let me know if I'm doing something wrong.

### To Reproduce

Here you can see a very simple example of a test that fails with the strange error
    
    class PlainTest extends Specification {

        def "test method"() {
            given:
            def str = "Some string"

            expect:
            str == null
        }
    }

### Expected behavior

A clear statement that the comparison is wrong.
Actual: "Some string"
Expected: null

### Actual behavior

Not clear error message:

    java.lang.NoSuchMethodError: 'org.opentest4j.ValueWrapper org.opentest4j.ValueWrapper.create(java.lang.Object, java.lang.String)'

	at org.spockframework.runtime.MasterRunSupervisor.convertToComparisonFailure(MasterRunSupervisor.java:92)
	at org.spockframework.runtime.MasterRunSupervisor.transform(MasterRunSupervisor.java:67)
	at org.spockframework.runtime.MasterRunSupervisor.error(MasterRunSupervisor.java:46)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:411)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392)
	at org.spockframework.runtime.PlatformSpecRunner.runFeatureMethod(PlatformSpecRunner.java:326)
	at org.spockframework.runtime.IterationNode.execute(IterationNode.java:48)
	at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:58)
	at org.spockframework.runtime.SimpleFeatureNode.execute(SimpleFeatureNode.java:15)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
	at org.spockframework.runtime.IterationNode.lambda$around$0(IterationNode.java:63)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunIteration$5(PlatformSpecRunner.java:238)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:409)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392)
	at org.spockframework.runtime.PlatformSpecRunner.runIteration(PlatformSpecRunner.java:220)
	at org.spockframework.runtime.IterationNode.around(IterationNode.java:63)
	at org.spockframework.runtime.SimpleFeatureNode.lambda$around$0(SimpleFeatureNode.java:52)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
	at org.spockframework.runtime.FeatureNode.lambda$around$0(FeatureNode.java:29)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:201)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:409)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392)
	at org.spockframework.runtime.PlatformSpecRunner.runFeature(PlatformSpecRunner.java:194)
	at org.spockframework.runtime.FeatureNode.around(FeatureNode.java:29)
	at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:52)
	at org.spockframework.runtime.SimpleFeatureNode.around(SimpleFeatureNode.java:15)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
	at org.spockframework.runtime.SpecNode.lambda$around$0(SpecNode.java:63)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunSpec$0(PlatformSpecRunner.java:61)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148)
	at org.spockframework.runtime.PlatformSpecRunner.invokeRaw(PlatformSpecRunner.java:409)
	at org.spockframework.runtime.PlatformSpecRunner.invoke(PlatformSpecRunner.java:392)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:55)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:63)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:11)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

### Java version

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Buildtool version

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/user/.sdkman/candidates/maven/current
Java version: 16.0.1, vendor: AdoptOpenJDK, runtime: /home/user/.sdkman/candidates/java/16.0.1.hs-adpt
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-63-generic", arch: "amd64", family: "unix"

### What operating system are you using

Linux

### Dependencies

Our internal dependencies are hidden by `com.example`.
[dependency-report.txt](https://github.com/spockframework/spock/files/7005878/dependency-report.txt)

### Additional context

Apart from that, I found another very strange issue. The compiler pays attention that 

`MasterRunSupervisor.convertToComparisonFailure(MasterRunSupervisor.java:92)` calls not existing method `ValueWrapper.create(actualValue, renderValue(actualValue));`
![MasterRunSupervisor](https://user-images.githubusercontent.com/9593317/129867184-cb6d06d8-7265-4084-ba3a-f97bc5aa1307.png)

**Comment by leonard84** [comment]
This looks like there is an older version of `org.opentest4j:opentest4j` on the classpath, the dependency report shows the correct version `1.2.0`.  What dependency is shown when you navigate to `ValueWrapper` in your IDE?

The reproducer works fine in the groovy console https://gwc-experiment.appspot.com/ so I would assume there is something wrong with this build.

**Comment by driversti** [comment]
Hi @leonard84 
Thank you for reaching me out :)
You're right. It turned out that we have an older version of `org.opentest4j:opentest4j` in our classpath but in some strange way.
There is `org.springframework.cloud:spring-cloud-contract-wiremock:3.0.3` in our `pom.xml`. One of its dependencies is `com.github.tomakehurst:wiremock-jre8-standalone:2.27.1`. There is a package `org.opentest4j` in the `wiremock-jre8-standalone` jar which contains an old version of the `ValueWrapper` class. Removing `org.springframework.cloud:spring-cloud-contract-wiremock:3.0.3` dependency from the `pom.xml` resolved the issue.
At the moment we do not use **Wiremock** in our project, but there is a high probability we will do this in a short term. Do you have any solution how to make everything work together with Wiremock?

**Comment by leonard84** [comment]
You could try to upgrade the wiremock dependency, or replace the standalone version, by the "normal" version, this way maven should be able to use the correct opentest4j version.

**Comment by driversti** [comment]
Currently I removed `org.springframework.cloud:spring-cloud-contract-wiremock:3.0.3` since we do not use it. It's not possible to update the dependency with the correct version of `org.opentest4j` as these classes are copied inside the dependency. Probably I need to contact the maintainer of `spring-cloud-contract-wiremock` to resolve the issue.
Again, thanks a lot for your support :)
