### ISSUE TITLE
Unable to compile test in IntelliJ IDEA

### ISSUE THREAD

**Issue by jan-krakora** [spockframework/spock#1385]
### Describe the bug

I'm trying to migrate from Spock 1 to Spock 2 in our Maven project we develop in the IDEA IDE. Using `mvn clean test` all is compiled correctly and the test pass. However, test compile in IDEA throws an error.

### To Reproduce

Test.groovy file in src/test/java
```
import spock.lang.Specification

class Test extends Specification {

	def "test"() {
		expect:
			"" instanceof String
	}
}
```
Pom file
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cz.diribet</groupId>
    <artifactId>test</artifactId>
    <version>1.1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>2.0-groovy-3.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>3.0.8</version>
            <type>pom</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>

                <configuration>
                    <source>16</source>
                    <target>16</target>
                    <encoding>UTF-8</encoding>
                </configuration>

                <executions>
                    <execution>
                        <id>test-compile</id>
                        <phase>process-test-sources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <source>13</source>
                            <target>13</target>
                            <compilerId>groovy-eclipse-compiler</compilerId>
                        </configuration>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>3.7.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>3.0.8-01</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

### Expected behavior

The test shold be compiled, and should pass.

### Actual behavior

Groovyc: While compiling [tests of test]: Unexpected error during compilation of spec 'Test'. Maybe you have used invalid Spock syntax? Anyway, please file a bug report at http://issues.spockframework.org.

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at org.spockframework.compiler.ConditionRewriter.visitClassExpression(ConditionRewriter.java:253)
	at org.codehaus.groovy.ast.expr.ClassExpression.visit(ClassExpression.java:35)
	at org.spockframework.util.AbstractExpressionConverter.convert(AbstractExpressionConverter.java:37)
	at org.spockframework.compiler.ConditionRewriter.visitBinaryExpression(ConditionRewriter.java:223)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:58)
	at org.spockframework.util.AbstractExpressionConverter.convert(AbstractExpressionConverter.java:37)
	at org.spockframework.compiler.ConditionRewriter.rewriteOtherCondition(ConditionRewriter.java:665)
	at org.spockframework.compiler.ConditionRewriter.rewriteCondition(ConditionRewriter.java:608)
	at org.spockframework.compiler.ConditionRewriter.rewriteCondition(ConditionRewriter.java:589)
	at org.spockframework.compiler.ConditionRewriter.rewriteImplicitCondition(ConditionRewriter.java:78)
	at org.spockframework.compiler.DeepBlockRewriter.handleImplicitCondition(DeepBlockRewriter.java:219)
	at org.spockframework.compiler.DeepBlockRewriter.doVisitExpressionStatement(DeepBlockRewriter.java:84)
	at org.spockframework.compiler.AbstractDeepBlockRewriter.visitExpressionStatement(AbstractDeepBlockRewriter.java:100)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.spockframework.compiler.StatementReplacingVisitorSupport.replace(StatementReplacingVisitorSupport.java:44)
	at org.spockframework.compiler.AbstractDeepBlockRewriter.visit(AbstractDeepBlockRewriter.java:84)
	at org.spockframework.compiler.DeepBlockRewriter.visit(DeepBlockRewriter.java:55)
	at org.spockframework.compiler.SpecRewriter.visitAnyBlock(SpecRewriter.java:386)
	at org.spockframework.compiler.model.ExpectBlock.accept(ExpectBlock.java:31)
	at org.spockframework.compiler.model.Method.accept(Method.java:70)
	at org.spockframework.compiler.model.Spec.accept(Spec.java:112)
	at org.spockframework.compiler.SpockTransform$Impl.processSpec(SpockTransform.java:76)
	at org.spockframework.compiler.SpockTransform$Impl.visit(SpockTransform.java:63)
	at org.spockframework.compiler.SpockTransform.visit(SpockTransform.java:48)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at org.jetbrains.groovy.compiler.rt.GroovyCompilerWrapper.compile(GroovyCompilerWrapper.java:48)
	at org.jetbrains.groovy.compiler.rt.DependentGroovycRunner.runGroovyc(DependentGroovycRunner.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.groovy.compiler.rt.GroovycRunner.intMain2(GroovycRunner.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.runGroovycInThisProcess(InProcessGroovyc.java:167)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.lambda$runGroovyc$0(InProcessGroovyc.java:77)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

I have debug the compile process in IDEA and is seems that problem is somehow related to the part
`"" instanceof String` where Spock is trying to rewrite the implicit condition and works with the ASTNode from Groovy. This object contains information about line/last line and column/last column of the expression. Those informations are in this case

- lineNumber: 1
- lastLineNumber: 1
- columnNumber: 99
- lastColumnNumber: 119

Which is wrong, since at line 1 is the import expression `import spock.lang.Specification` which has fewer than 99 characters. So there is an StringIndexOutOfBoundsException at org.spockframework.compiler.SourceLookup:45 resulting in above NPE 

### Java version

Build on Open JDK 16, target for tests is Java 13

### Buildtool version

Maven 3.8.3

### What operating system are you using

Windows

### Dependencies

[dependency-report.txt](https://github.com/spockframework/spock/files/7353088/dependency-report.txt)

**Comment by jan-krakora** [comment]
The problem was in wrong line separator. I accidentally use CR, instead of CRLF (I'm working on Windows). Anyway, with Groovy 2.5 and Spock 1.3 it works even with this wrong line separator.
