### ISSUE TITLE
Spock is using old impl org.codehaus.jackson

### ISSUE THREAD

**Issue by mikesz14** [spockframework/spock#1411]
Caused by: java.lang.NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper
        at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)
        at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:240)
        at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:124)
        at org.spockframework.compiler.SpecialMethodCall.checkIsConditionBlock(SpecialMethodCall.java:269)
        at org.spockframework.compiler.SpecialMethodCall.parse(SpecialMethodCall.java:172)
        at org.spockframework.compiler.AbstractDeepBlockRewriter.visitMethodCallExpression(AbstractDeepBlockRewriter.java:123)
        at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitBinaryExpression(AbstractDeepBlockRewriter.java:166)

Where maven repo suggest usage of newer impl 
https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl

It requires additional dependencies to be added with new spring boot

**Comment by leonard84** [comment]
Hi Mikesz, please add the additional information from the bug report issue template, at least:

>Dependencies
>
>Which Dependencies are you using?
>
>Either manually list the relevant dependencies below,
or use one of these commands to create a dependencies-report.txt and attach it
>
>    ./gradlew -q dependencies --configuration testRuntimeClasspath > dependencies-report.txt
>    mvn dependency:tree -DoutputFile=dependency-report.txt

**Comment by jishnunitc** [comment]
@mikesz14 which were additional dependencies you had to add ?

**Comment by leonard84** [comment]
@mikesz14 I'm pretty sure that Spock is not the cause and instead your application code is responsible. The Stacktrace might be a bit misleading, but this happens during compilation of your code.
