### ISSUE TITLE
Spock Spring does not setup Spring Context for Spring 6.0.0

### ISSUE THREAD

**Issue by marcingrzejszczak** [spockframework/spock#1417]
### Describe the bug

When setting up a new project using Boot 3.0.0 and Spring Framework 6.0.0 Spring context is not started at all. I did some initial investigation and first of all a `org.spockframework.spring.SpringExtension#isSpringSpec` returns `false` now. Also when putting the `@ContextConfiguration` manually on the test class, even though that `isSpringSpec` would return `true` it fails on a `ClassNotFoundException` as follows:

```
java.lang.NoClassDefFoundError: org/springframework/beans/factory/config/InstantiationAwareBeanPostProcessorAdapter
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at org.spockframework.spring.mock.SpockContextCustomizer.customizeContext(SpockContextCustomizer.java:43)
    at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:294)
    at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:599)
    at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
    at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:124)
    at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
    at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:123)
    at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
    at org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener.applicationContextBroken(WireMockTestExecutionListener.java:120)
    at org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener.beforeTestClass(WireMockTestExecutionListener.java:43)
    at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:213)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### To Reproduce

You can check this project for reference https://github.com/marcingrzejszczak/spock-spring-6-issue 

### Expected behavior

The context is set up and the test passes

### Actual behavior

The context is not set up and the test fails

### Java version

$  java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS)
OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)

### Buildtool version

$ ./mvnw --version
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /home/marcin/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3
Java version: 17, vendor: Azul Systems, Inc., runtime: /home/marcin/.sdkman/candidates/java/17.0.0-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-27-generic", arch: "amd64", family: "unix"

### What operating system are you using

Linux

### Dependencies

```
com.example:demo:jar:0.0.1-SNAPSHOT
+- org.springframework.boot:spring-boot-starter:jar:3.0.0-SNAPSHOT:compile
|  +- org.springframework.boot:spring-boot:jar:3.0.0-SNAPSHOT:compile
|  |  \- org.springframework:spring-context:jar:6.0.0-M2:compile
|  |     +- org.springframework:spring-aop:jar:6.0.0-M2:compile
|  |     +- org.springframework:spring-beans:jar:6.0.0-M2:compile
|  |     \- org.springframework:spring-expression:jar:6.0.0-M2:compile
|  +- org.springframework.boot:spring-boot-autoconfigure:jar:3.0.0-SNAPSHOT:compile
|  +- org.springframework.boot:spring-boot-starter-logging:jar:3.0.0-SNAPSHOT:compile
|  |  +- ch.qos.logback:logback-classic:jar:1.2.10:compile
|  |  |  \- ch.qos.logback:logback-core:jar:1.2.10:compile
|  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.1:compile
|  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
|  |  \- org.slf4j:jul-to-slf4j:jar:1.7.33:compile
|  +- jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile
|  +- org.springframework:spring-core:jar:6.0.0-M2:compile
|  |  \- org.springframework:spring-jcl:jar:6.0.0-M2:compile
|  \- org.yaml:snakeyaml:jar:1.30:compile
+- org.springframework.boot:spring-boot-starter-test:jar:3.0.0-SNAPSHOT:test
|  +- org.springframework.boot:spring-boot-test:jar:3.0.0-SNAPSHOT:test
|  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.0.0-SNAPSHOT:test
|  +- com.jayway.jsonpath:json-path:jar:2.6.0:test
|  |  +- net.minidev:json-smart:jar:2.4.7:test
|  |  |  \- net.minidev:accessors-smart:jar:2.4.7:test
|  |  |     \- org.ow2.asm:asm:jar:9.1:test
|  |  \- org.slf4j:slf4j-api:jar:1.7.33:compile
|  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1:test
|  |  \- com.sun.activation:jakarta.activation:jar:2.0.1:test
|  +- org.assertj:assertj-core:jar:3.22.0:test
|  +- org.hamcrest:hamcrest:jar:2.2:test
|  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
|  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
|  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
|  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
|  +- org.mockito:mockito-core:jar:4.2.0:test
|  |  +- net.bytebuddy:byte-buddy:jar:1.12.7:test
|  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.7:test
|  |  \- org.objenesis:objenesis:jar:3.2:test
|  +- org.mockito:mockito-junit-jupiter:jar:4.2.0:test
|  +- org.skyscreamer:jsonassert:jar:1.5.0:test
|  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
|  +- org.springframework:spring-test:jar:6.0.0-M2:test
|  \- org.xmlunit:xmlunit-core:jar:2.8.4:test
+- org.spockframework:spock-core:jar:2.0-groovy-3.0:test
|  +- org.codehaus.groovy:groovy:jar:3.0.9:test
|  \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
|     +- org.opentest4j:opentest4j:jar:1.2.0:test
|     +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
|     \- org.apiguardian:apiguardian-api:jar:1.1.2:test
\- org.spockframework:spock-spring:jar:2.0-groovy-3.0:test
```

**Comment by sbrannen** [comment]
See also:

- https://github.com/spring-projects/spring-framework/issues/25165
- https://github.com/spring-projects/spring-framework/commit/4750a9430cdae9156d1e7fc32cec2c11ba2b8514#diff-278a4b92135d1ef8508fc5f63b1ecd6582b5f11f20d07e2d8aad38aa058a70ae

**Comment by leonard84** [comment]
So to stay backwards compatible we have to basically recreate the InstantiationAwareBeanPostProcessorAdapter for Spock, as the older Spring interface don't support the default methods.
