### ISSUE TITLE
callRealMethod() doesn't work with Java 17

### ISSUE THREAD

**Issue by vprudnikov** [spockframework/spock#1429]
### Describe the bug

I upgraded to Java 17, and all the tests using` callRealMethod()` failed.

### To Reproduce

Example of the code that worked with Java 15:
```
    def setup() {
        context = Stub(Context) {
            hasPermission(_ as ResourceType) >> { callRealMethod() }
        }
    ...
```
`Context `is an interface:
```
public interface Context {
    ...
    default boolean hasPermission(@NonNull ResourceType resourceType) {
        return //implementation goes here;
    }
    ...
```

### Expected behavior

The code doesn't fail

### Actual behavior

```
Caused by: org.spockframework.mock.CannotCreateMockException: Cannot create mock for class jdk.proxy2.$Proxy20Failed to invoke default method 'hasPermission'
	at org.spockframework.mock.runtime.DefaultMethodInvoker.respond(DefaultMethodInvoker.java:64)
	at org.spockframework.mock.runtime.MockInvocation.callRealMethod(MockInvocation.java:59)
	at MySpec.setup_closure1$_closure3(MySpec.groovy:29)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.spockframework.mock.response.CodeResponseGenerator.invokeClosure(CodeResponseGenerator.java:54)
	at org.spockframework.mock.response.CodeResponseGenerator.doRespond(CodeResponseGenerator.java:37)
	at org.spockframework.mock.response.SingleResponseGenerator.respond(SingleResponseGenerator.java:32)
	at org.spockframework.mock.response.ResponseGeneratorChain.respond(ResponseGeneratorChain.java:44)
	at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:73)
	at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:50)
	at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:57)
	at org.spockframework.mock.runtime.MockController.handle(MockController.java:40)
	at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:84)
	at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
	at MyImpl.verify(MyImpl.java:23)
	at MySpec.OK if there is an access (MySpec.groovy:87)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @3567135c
	at org.spockframework.mock.runtime.DefaultMethodInvoker.respond(DefaultMethodInvoker.java:50)
	... 15 more
```

### Java version

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Buildtool version

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/apache-maven-3.8.4
Java version: 17.0.2, vendor: Oracle Corporation, runtime: /home/apotek1/.sdkman/candidates/java/17.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-89-generic", arch: "amd64", family: "unix"

### What operating system are you using

Linux

### Dependencies

        <groovy.version>3.0.9</groovy.version>
        <spock.version>2.2-M1-groovy-3.0</spock.version>

### Additional context

The problem can be mitigated by settings the following arg line to the `maven-surefire-plugin`:

```
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        ...
                        <argLine>--illegal-access=warn --add-opens java.base/java.lang.invoke=ALL-UNNAMED</argLine>
                    </configuration>
                </plugin>

```

**Comment by leonard84** [comment]
Duplicates #1406
