### ISSUE TITLE
Reusable Data Tables problem

### ISSUE THREAD

**Issue by w00cash** [spockframework/spock#1527]
### Describe the bug

Data pipe is giving error

### To Reproduce

@Unroll
    def "max of #a and #b gives #c"() {
        expect:
        Math.max(a, b) == c
        where:
        [a, b, c] << dataTable()
    }

    static def dataTable() {
        [
                [1, 0, 1],
                [2, 2, 2],
                [4, 5, 5]
        ]
    }
}

### Expected behavior

3 test should run

### Actual behavior

Internal Error occurred.
org.junit.platform.commons.JUnitException: TestEngine with ID 'spock' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.junit.platform.commons.JUnitException: MethodSelector [className = 'specs.drug.DrugSearchSpec', methodName = 'max of #a and #b givesaa #c', methodParameterTypes = ''] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.spockframework.runtime.SpockEngine.discover(SpockEngine.java:28)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 11 more
Caused by: java.lang.VerifyError: (class: specs/drug/DrugSearchSpec, method: $spock_feature_1_5prov0 signature: ()Ljava/lang/Object;) Illegal target of jump or branch
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
	at org.spockframework.runtime.SpecInfoBuilder.buildFields(SpecInfoBuilder.java:86)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:57)
	at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:42)
	at org.spockframework.runtime.ClassSelectorResolver.lambda$resolveClass$1(ClassSelectorResolver.java:44)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:246)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:209)
	at org.spockframework.runtime.ClassSelectorResolver.resolveClass(ClassSelectorResolver.java:43)
	at org.spockframework.runtime.ClassSelectorResolver.resolve(ClassSelectorResolver.java:26)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.access$100(EngineDiscoveryRequestResolution.java:57)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.resolve(EngineDiscoveryRequestResolution.java:224)
	at org.spockframework.runtime.MethodSelectorResolver.resolve(MethodSelectorResolver.java:76)
	at org.spockframework.runtime.MethodSelectorResolver.resolveWithIterationFilter(MethodSelectorResolver.java:61)
	at org.spockframework.runtime.MethodSelectorResolver.resolveAllowingAllIndexes(MethodSelectorResolver.java:57)
	at org.spockframework.runtime.MethodSelectorResolver.resolve(MethodSelectorResolver.java:27)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:146)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 15 more

### Java version

openjdk 11.0.11 2021-04-20

### Buildtool version

apache Maven 3.8.2

### What operating system are you using

Mac

### Dependencies

org.spockframework:pdp-test-automation-spock:jar:1.0-SNAPSHOT
+- com.athaydes:spock-reports:jar:2.3.0-groovy-3.0:test
+- org.slf4j:slf4j-api:jar:1.7.30:test
+- org.slf4j:slf4j-simple:jar:1.7.30:test
+- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
+- org.spockframework:spock-core:jar:2.2-groovy-3.0:test
|  +- org.junit.platform:junit-platform-engine:jar:1.9.0:test
|  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
|  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test
|  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
|  \- org.hamcrest:hamcrest:jar:2.2:test
+- ru.vyarus:spock-junit5:jar:1.1.0:test
|  \- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test
+- org.seleniumhq.selenium:selenium-java:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-api:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.1.1:test
|  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:test
|  |  +- com.google.auto.service:auto-service:jar:1.0.1:test
|  |  |  \- com.google.auto:auto-common:jar:1.2:test
|  |  +- com.google.guava:guava:jar:31.0.1-jre:compile
|  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
|  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
|  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
|  |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
|  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.7.1:compile
|  |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
|  |  +- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.1.1:test
|  |  \- org.seleniumhq.selenium:selenium-json:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-devtools-v94:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-devtools-v95:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-devtools-v96:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-firefox-xpi-driver:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-opera-driver:jar:4.1.1:test
|  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.1.1:test
|  |  +- com.beust:jcommander:jar:1.81:test
|  |  +- io.netty:netty-buffer:jar:4.1.70.Final:test
|  |  +- io.netty:netty-codec-http:jar:4.1.70.Final:test
|  |  |  +- io.netty:netty-codec:jar:4.1.70.Final:test
|  |  |  \- io.netty:netty-handler:jar:4.1.70.Final:test
|  |  +- io.netty:netty-common:jar:4.1.70.Final:test
|  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.70.Final:test
|  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.70.Final:test
|  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.70.Final:test
|  |  +- io.netty:netty-transport:jar:4.1.70.Final:test
|  |  |  \- io.netty:netty-resolver:jar:4.1.70.Final:test
|  |  +- io.opentelemetry:opentelemetry-api:jar:1.9.1:test
|  |  +- io.opentelemetry:opentelemetry-context:jar:1.9.1:test
|  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.9.1:test
|  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.9.1-alpha:test
|  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.9.1-alpha:test
|  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.9.1:test
|  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.9.1:test
|  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.9.1-alpha:test
|  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.9.1:test
|  |  |  \- io.opentelemetry:opentelemetry-api-metrics:jar:1.9.1-alpha:test
|  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.9.1:test
|  |  +- io.opentelemetry:opentelemetry-semconv:jar:1.9.1-alpha:test
|  |  +- io.ous:jtoml:jar:2.0.0:test
|  |  +- net.bytebuddy:byte-buddy:jar:1.12.2:test
|  |  +- org.apache.commons:commons-exec:jar:1.3:test
|  |  +- org.asynchttpclient:async-http-client:jar:2.12.3:test
|  |  |  +- org.asynchttpclient:async-http-client-netty-utils:jar:2.12.3:test
|  |  |  +- io.netty:netty-codec-socks:jar:4.1.60.Final:test
|  |  |  +- io.netty:netty-handler-proxy:jar:4.1.60.Final:test
|  |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:test
|  |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:test
|  |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:test
|  |  |  +- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:test
|  |  |  \- com.sun.activation:jakarta.activation:jar:1.2.2:test
|  |  \- org.seleniumhq.selenium:selenium-http:jar:4.1.1:test
|  |     \- net.jodah:failsafe:jar:2.4.4:test
|  +- org.seleniumhq.selenium:selenium-safari-driver:jar:4.1.1:test
|  \- org.seleniumhq.selenium:selenium-support:jar:4.1.1:test
+- org.codehaus.groovy:groovy:jar:3.0.12:test
+- io.rest-assured:rest-assured:jar:4.4.0:test
|  +- org.codehaus.groovy:groovy-xml:jar:3.0.8:compile
|  +- org.apache.httpcomponents:httpclient:jar:4.5.13:test
|  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:test
|  |  \- commons-logging:commons-logging:jar:1.2:test
|  +- org.apache.httpcomponents:httpmime:jar:4.5.13:test
|  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
|  +- io.rest-assured:json-path:jar:4.4.0:test
|  |  +- org.codehaus.groovy:groovy-json:jar:3.0.8:test
|  |  \- io.rest-assured:rest-assured-common:jar:4.4.0:test
|  \- io.rest-assured:xml-path:jar:4.4.0:test
|     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
|     |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
|     \- com.sun.xml.bind:jaxb-impl:jar:2.3.3:test
+- org.codehaus.groovy.modules.http-builder:http-builder:jar:0.7.1:test
|  +- net.sf.json-lib:json-lib:jar:jdk15:2.3:test
|  |  +- commons-beanutils:commons-beanutils:jar:1.8.0:test
|  |  +- commons-collections:commons-collections:jar:3.2.1:test
|  |  +- commons-lang:commons-lang:jar:2.4:test
|  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:test
|  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.16:test
|  |  \- xerces:xercesImpl:jar:2.9.1:test
|  |     \- xml-apis:xml-apis:jar:1.3.04:test
|  \- xml-resolver:xml-resolver:jar:1.2:test
+- org.apache.poi:poi:jar:5.1.0:compile
|  +- commons-codec:commons-codec:jar:1.15:compile
|  +- org.apache.commons:commons-collections4:jar:4.4:compile
|  +- org.apache.commons:commons-math3:jar:3.6.1:compile
|  +- commons-io:commons-io:jar:2.11.0:compile
|  \- com.zaxxer:SparseBitSet:jar:1.2:compile
+- org.apache.poi:poi-ooxml:jar:5.1.0:compile
|  +- org.apache.poi:poi-ooxml-lite:jar:5.1.0:compile
|  +- org.apache.xmlbeans:xmlbeans:jar:5.0.2:compile
|  +- org.apache.commons:commons-compress:jar:1.21:compile
|  \- com.github.virtuald:curvesapi:jar:1.06:compile
+- com.jayway.jsonpath:json-path:jar:2.7.0:compile
|  \- net.minidev:json-smart:jar:2.4.7:compile
|     \- net.minidev:accessors-smart:jar:2.4.7:compile
|        \- org.ow2.asm:asm:jar:9.1:compile
+- org.codehaus.groovy:groovy-templates:jar:2.4.3:compile
\- io.github.bonigarcia:webdrivermanager:jar:5.2.3:compile
   +- com.google.code.gson:gson:jar:2.9.1:compile
   +- com.github.docker-java:docker-java:jar:3.2.13:compile
   |  +- com.github.docker-java:docker-java-core:jar:3.2.13:compile
   |  |  +- com.github.docker-java:docker-java-api:jar:3.2.13:compile
   |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
   |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
   |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.10.3:compile
   |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
   |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
   |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
   +- com.github.docker-java:docker-java-transport-httpclient5:jar:3.2.13:compile
   |  +- com.github.docker-java:docker-java-transport:jar:3.2.13:compile
   |  \- net.java.dev.jna:jna:jar:5.8.0:compile
   +- org.brotli:dec:jar:0.1.2:compile
   +- org.apache.commons:commons-lang3:jar:3.12.0:compile
   \- org.apache.httpcomponents.client5:httpclient5:jar:5.1.3:compile
      +- org.apache.httpcomponents.core5:httpcore5:jar:5.1.3:compile
      \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.1.3:compile

tried both Junit 4 and 5

### Additional context

this works :

@Unroll
    def "max of #a and #b givesaa #c"() {
        expect:
        Math.max(a, b) == c
        where:
        [a, b, c] << [
                [1, 0, 1],
                [2, 2, 2],
                [4, 5, 5]
        ]
    }

**Comment by w00cash** [comment]
After reading Leanard answare here: https://stackoverflow.com/questions/73705596/spock-failed-to-discover-tests-when-method-call-used-in-where-clause

I have investigated more.... After Updating groovy version to 4.0.5 It works fine.

Shall we close in that case?
