### ISSUE TITLE
Why Jdk17 jdk.proxy2 does not read module agent.tw

### ISSUE THREAD

**Issue by pangxianhai** [spockframework/spock#1592]
### Is your feature request related to a problem?

[2023-03-08 18:11:02 273] [WARNING] [main] [systemout] [java.lang.IllegalAccessError: class jdk.proxy2.$Proxy3 (in module jdk.proxy2) cannot access class com.tongapm.agent.profiler.core.instrument.transformer.MethodProfiler (in module agent.tw) because module jdk.proxy2 does not read module agent.tw]
[2023-03-08 18:11:02 273] [WARNING] [main] [systemout] [        at jdk.proxy2/jdk.proxy2.$Proxy3.annotationType(Unknown Source)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:123)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at java.base/java.lang.Class.createAnnotationData(Class.java:4068)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at java.base/java.lang.Class.annotationData(Class.java:4057)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at java.base/java.lang.Class.getAnnotation(Class.java:3940)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassAnnotation(RuntimeInlineAnnotationReader.java:106)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassAnnotation(RuntimeInlineAnnotationReader.java:57)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:385)]
[2023-03-08 18:11:02 274] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:465)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:142)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1174)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at java.base/java.lang.reflect.Method.invoke(Method.java:568)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)]
[2023-03-08 18:11:02 275] [WARNING] [main] [systemout] [        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at javax.xml.bind.ContextFinder.find(ContextFinder.java:442)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.config.ConfigTool.readXmlFile(ConfigTool.java:691)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.config.ConfigTool.readXmlFile(ConfigTool.java:552)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.config.ConfigTool.getRoot(ConfigTool.java:524)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.catalina.startup.ThanosCatalina.e(Unknown Source)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.catalina.startup.ThanosCatalina.load(Unknown Source)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at com.tongweb.catalina.startup.Catalina.load(Catalina.java:634)]
[2023-03-08 18:11:02 276] [WARNING] [main] [systemout] [        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)]

### Describe the solution you'd like

the agent.tw is a module made by myself

under agent.tw com.tongapm.agent.profiler.core.instrument.transformer had exports

```
  exports com.tongapm.agent;
    exports com.tongapm.agent.profiler.core.instrument.transformer;
    exports com.tongapm.agent.profiler.core.instrument;

    opens com.tongapm.agent.profiler.core.instrument.transformer;
    opens com.tongapm.agent.profiler.core.instrument;
```

**Comment by leonard84** [comment]
Hi @pangxianhai please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), otherwise I don't see a way to investigate this issue.
