### ISSUE TITLE
'No runnable methods' When Using Suite

### ISSUE THREAD

**Issue by felipelo** [spockframework/spock#1963]
### Describe the bug

Hello,

I am trying to use Suite and specify all classes I want to execute tests, but it is giving me 'No runnable methods'.

I am using the spock-example as a starting point, I created a class called MySuite.groovy and specified 'DatabaseDriveSpec. Other than this change, I have also modified pom.xml plugin surefire to only include MySuite.

When running mvn test, I am getting this error:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running MySuite
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.150 s <<< FAILURE! -- in MySuite
[ERROR] DatabaseDrivenSpec.initializationError -- Time elapsed: 0.009 s <<< ERROR!
org.junit.runners.model.InvalidTestClassError: 
Invalid test class 'DatabaseDrivenSpec':
  1. No runnable methods
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
        at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
        at org.junit.runners.Suite.<init>(Suite.java:102)
        at org.junit.runners.Suite.<init>(Suite.java:70)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
        at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:314)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

Is that something that is not supported by new version of Spock? What is the alternative?

### To Reproduce

Clone spock-example code, add class MySuite and change Surefire plugin to include only MySuite. Run mvn clean test.

### Expected behavior

MySuite code:

```
import org.junit.runner.RunWith
import org.junit.runners.Suite

@RunWith(Suite.class)
@Suite.SuiteClasses([
        DatabaseDrivenSpec.class
])

class MySuite {
}
```

### Actual behavior

Expecting to have tests running based on MySuite class.

### Java version

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

### Buildtool version

```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

### What operating system are you using

Mac

### Dependencies

```
org.spockframework:spock-example:jar:1.0-SNAPSHOT
+- org.spockframework:spock-core:jar:2.3-groovy-4.0:test
|  +- org.junit.platform:junit-platform-engine:jar:1.9.0:test
|  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
|  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test
|  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
|  \- org.hamcrest:hamcrest:jar:2.2:test
+- org.spockframework:spock-junit4:jar:2.3-groovy-4.0:compile
|  \- junit:junit:jar:4.13.2:compile
+- org.apache.groovy:groovy:jar:4.0.21:compile
+- net.bytebuddy:byte-buddy:jar:1.14.17:test
+- org.objenesis:objenesis:jar:3.4:test
+- org.hamcrest:hamcrest-core:jar:2.2:test
+- com.h2database:h2:jar:2.2.224:compile
\- org.apache.groovy:groovy-sql:jar:4.0.21:compile
```

**Comment by AndreasTu** [comment]
JUnit Suites are a deprecated JUnit 4 concept.
Since Spock 2.0 it works with JUnit Platform (JUnit 5), so JUnit 4 Suites are **not** supported anymore by Spock.
Spock specifications since Spock 2.0 are autodiscovered by JUnit Platform (JUnit 5), see JUnit documentation for details.

Please have a look at the [JUnit 4 migration guide](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) from the JUnit team on how to migrate from JUnit4 to JUnit Platform + JUnit Jupiter.

**Comment by Vampire** [comment]
The [JUnit Platform Suite Engine](https://junit.org/junit5/docs/current/user-guide/#junit-platform-suite-engine) is what you are after. It is the JUnit Platform equivalent of the `Suite` runner and it works perfectly fine with Spock 2+.

**Comment by felipelo** [comment]
> The [JUnit Platform Suite Engine](https://junit.org/junit5/docs/current/user-guide/#junit-platform-suite-engine) is what you are after. It is the JUnit Platform equivalent of the `Suite` runner and it works perfectly fine with Spock 2+.

Thanks, that really helps. Do you think it would be beneficial to have it in the spock-example? I can work on a PR if you like it.
