### ISSUE TITLE
Error when running single method from base spec

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#198]
Originally reported on Google Code with ID 76

```
class BaseSpec extends Specification {
  def "foo"() {
    expect: false
  }
}

class DerivedSpec extends BaseSpec {
    def bar() {
        expect: false
    }
}

First run class DerivedSpec. Then select method "foo" from IDEA's JUnit view and run
it. Result:

java.lang.Exception: No tests found matching Method foo(DerivedSpec) from 
org.junit.internal.requests.ClassRequest@583e97df
    at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:37)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:60)

Seems we don't search for methods in base spec when the filter is applied.

```

Reported by `pniederw` on 2010-03-02 12:21:02

**Comment by javeed1** [comment]
what is the solution, can you please share the fix with us
