### ISSUE TITLE
Already Value ... bound to thread

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#333]
Originally reported on Google Code with ID 211

```
What steps will reproduce the problem? If possible, provide source code and
stack trace.
=======================
import grails.plugin.spock.*
import grails.test.mixin.Mock
import grails.test.mixin.TestFor
import spock.lang.*

@TestFor(Company)
@Mock(Fleet)
class CompanySpec extends Specification {


    def "should accept Fleet"() {
        given:
        Company acmeCompany = new Company(name:"ACME")
            .addToFleets(new Fleet(name:"Fleet One"))
            .save(flush:true)

        expect:
        acmeCompany.fleets.size() == 1
        acmeCompany.fleets.iterator().next().company != null    

    }
}
=======================

When the above test is run together with other tests it results in the stacktrace below.
 Running test-app on a project with 100+ specs resulted in the GebSpec, IntegrationSpec
and old-style UnitSpec tests running correctly but specs extending spock.lang.Specification
failed in the same manner.  Unfortunately I was unable to reproduce the error in a
simple project with the above spec.

What version of Spock and Groovy are you using?
Groovy 1.8 Spock 0.6-SNAPSHOT (2011-10-29)
Note that rolling back to 0.6-SNAPSHOT (2011-10-25) results in successful execution.

Please provide any additional information below. You can also assign
labels.


java.lang.reflect.InvocationTargetException
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:66)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:66)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:173)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:173)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.IllegalStateException: Already value [org.grails.datastore.mapping.transactions.SessionHolder@444ef630]
for key [org.grails.datastore.mapping.simple.SimpleMapDatastore@10ea443f] bound to
thread [main]
    at org.springframework.transaction.support.TransactionSynchronizationManager.bindResource(TransactionSynchronizationManager.java:179)
    at org.grails.datastore.mapping.core.DatastoreUtils.bindSession(DatastoreUtils.java:336)
    at grails.test.mixin.domain.DomainClassUnitTestMixin.connectDatastore(DomainClassUnitTestMixin.groovy:93)
    at fleet.CompanySpec.connectDatastore(CompanySpec.groovy)
    ... 10 more



```

Reported by `colin.webber@freedomit.co.za` on 2011-10-29 06:12:49

**Comment by leonard84** [comment]
Seems to be fixed
