### ISSUE TITLE
Using objenesis prevents running tests from interactive prompt more than once

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#428]
Originally reported on Google Code with ID 306

```
What steps will reproduce the problem? If possible, provide source code and stack trace.

If I include the objenesis dependency in my BuildConfig, my tests run fine when executed
as 'grails test-app' but fail after the first run if I go into interactive mode by
typing 'grails' and then issuing 'test-app' calls. This has happened in two distinct
apps.

The stacktrace is here (I cannot get Grails to give me the entire stacktrace either
using -Dgrails.full.stacktrace=true or specifying grails.full.stacktrace = true in
Config.groovy):

org.spockframework.mock.CannotCreateMockException: Cannot create mock for class grails.plugins.springsecurity.SpringSecurityServicenull
    at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:38)
    at org.spockframework.mock.runtime.ProxyBasedMockFactory$CglibMockFactory.createMock(ProxyBasedMockFactory.java:92)
    at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:49)
    at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
    at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
    at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:47)
    at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:282)
    at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:99)
    at com.xxxx.SystemServiceSpec.setup(SystemServiceSpec.groovy:17)
Caused by: java.lang.ClassCastException
    at java.lang.Class.cast(Class.java:2990)
    at org.spockframework.mock.runtime.MockInstantiator$ObjenesisInstantiator.instantiate(MockInstantiator.java:45)
    at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:31)
    ... 8 more





What version of Spock and Groovy are you using?

Spock 0.7, Grails 2.2.0 and 2.1.1
```

Reported by `gregap` on 2013-03-29 11:45:43

**Comment by kriegaex** [comment]
I just found this issue by chance when searching for some other Objenesis-related information in the repository. Does this problem still occur or has it been fixed on purpose or due to some refactoring? Maybe someone can try with both Spock 1.3 and 2.0-M2.

**Comment by Vampire** [comment]
I'm not sure we have an active Grails-capable person here.
And Peter who at least had a plan is not on the project anymore.
I guess a Grails-savvy user needs to test and / or provide a reproducer project with detailed instructions what to do for non-Grails people.
