### ISSUE TITLE
Correctly handle methods returning Optional

### ISSUE THREAD

**Issue by Derbeth** [spockframework/spock#527]
When code under test calls a Spock mock method returning Java 8 optional (and when there is no interaction defined for this method), an error appears:

```
org.spockframework.mock.CannotCreateMockException: Cannot create mock for class java.util.Optional because Java mocks cannot mock final classes. If the code under test is written in Groovy, use a Groovy mock.
    at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:41)
    at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
    at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
    at org.spockframework.mock.EmptyOrDummyResponse.createDummy(EmptyOrDummyResponse.java:123)
    at org.spockframework.mock.EmptyOrDummyResponse.respond(EmptyOrDummyResponse.java:92)
    at org.spockframework.mock.runtime.MockController.handle(MockController.java:49)
    at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:72)
    at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:28)
```

There should be an entry for java.util.Optional in EmptyOrDummyResponse.respond().

**Comment by OlgaMaciaszek** [comment]
+1  - have same issue

**Comment by dchristm77** [comment]
+1 - same issue
