### ISSUE TITLE
Allow creation of Spock mocks in traits

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#578]
I tried to refactor some common setup code into a trait, but it appears that (as of 1.0/2.4) calling `Mock()` inside a trait is not supported:

```
Caused by: org.spockframework.runtime.InvalidSpecException: Mock objects can only be created inside a spec, and only during the lifetime of a feature (iteration)
	at spock.lang.MockingApi.invalidMockCreation(MockingApi.java:1233)
	at spock.lang.MockingApi.Mock(MockingApi.java:142)
	at spock.lang.MockingApi$Mock.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at my.trait.MyTrait$Trait$Helper.$init$(MocksStripe.groovy:22)
```

I get this error regardless of whether the `Mock()` call is in a field initializer or in the `setup()` method, though it's thrown during spec initialization in the former case and on execution in the latter.

**Comment by szpak** [comment]
As a workaround you could take a look at the @leonard84 's changes related to detached (Java) mocks (PR #546).
