### ISSUE TITLE
Concurrent interactions deadlock because of a synchronized method MockController#handle

### ISSUE THREAD

**Issue by ptrts** [spockframework/spock#583]
The version is 1.0-groovy-2.4

``` groovy
import spock.lang.Specification

import java.util.concurrent.CountDownLatch
import java.util.concurrent.Semaphore

class CodeRunnerSpec extends Specification {

    class CodeRunner {

        Runnable code

        Runnable fallback

        Semaphore semaphore = new Semaphore(1)

        void log(String message) {
            println Thread.currentThread().getName() + ' ' + message
        }

        /**
         * Runs the runnable in a new (!) thread. 
         * If the runnable is already running, runs fallback in the current (!) thread
         */
        void runCode() {

            log '=== runCode(): begin ===' 
            log 'trying to acquire the semaphore'

            if (semaphore.tryAcquire()) {

                log 'starting the code in a new thread'

                Thread.start {

                    log 'we are in the thread, starting the code'

                    code.run()

                    log 'code has finished working, releasing the semaphore'

                    semaphore.release()
                }

                log 'the thread has been started'

            } else {

                log 'the semaphore is busy, running the fallback'

                fallback.run()

                log 'the fallback has finished'
            }

            log '=== runCode(): end ==='
        }
    }

    def "Should run the fallback the code is already running"() {

        given:

        CountDownLatch latch = new CountDownLatch(1)

        CodeRunner codeRunner = new CodeRunner();

        codeRunner.code = Stub(Runnable) {
            run() >> {
                codeRunner.log 'waiting...'
                latch.await()
                codeRunner.log 'finished waiting, exiting'
            }
        }

        codeRunner.fallback = Mock(Runnable)

        when:

        // the closure will start in a new (!) thread and start to wait on the latch
        codeRunner.runCode()

        Thread.sleep(10)

        // the closure is already running, so the fallback should be run in the current (!) thread
        codeRunner.runCode()

        ///////////////////////////////////////////////////////////////////////////////////
        // it won't get to here, as it will be waiting on entering a synchronized method:
        //
        //          org.spockframework.mock.runtime.MockController#handle
        //
        ///////////////////////////////////////////////////////////////////////////////////

        then:

        1 * codeRunner.fallback.run()

        cleanup:

        latch.countDown()
    }
}
```

**Comment by Fiouz** [comment]
This still happens with 1.1-groovy-2.4, but the core issue should be better expressed as **Mocks/stubs don't run concurrently in a multi-threaded context** as shown using the following specification.


```Groovy
import spock.lang.Specification
import spock.lang.Timeout
import spock.lang.Unroll

import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicInteger

@Unroll
class ConcurrentStubsSpec extends Specification {
    @Timeout(10)
    void "#scenario"() {
        given: "A system-under-test relying on multi-threading"

        def executorService = Executors.newFixedThreadPool(2)
        def counter = new AtomicInteger() // a counter to keep track of invocations order

        and: "A first slow collaborator with parameterized sleep time"

        def slowStubStarted = new CountDownLatch(1)
        def slowStub = Stub(name: 'Slow', Runnable) {
            run() >> {
                slowStubStarted.countDown()
                this.println "(${counter.incrementAndGet()}) Slow, sleeping for ${sleep}ms"
                Thread.sleep(sleep)
            }
        }

        and: "A second fast collaborator"

        def fastStub = Stub(name: 'Fast', Runnable) {
            run() >> {
                this.println "(${counter.incrementAndGet()}) Fast"
            }
        }

        when: "Submitting slow collaborator first"

        this.println "Start test with slow stub at ${sleep}ms"
        executorService.submit(slowStub)
        slowStubStarted.await() // make sure collaborator was started before proceeding to second one

        and: "Submitting second (fast) collaborator for concurrent execution"

        def fastFuture = executorService.submit(fastStub)

        and: "Waiting a finite amount of time, long enough for the fast collaborator to execute"

        Thread.sleep(1000 /* 1 second timeout which should be plenty for fastStub */)

        then: "Second (fast) collaborator should have completed"

        fastFuture.isDone()

        cleanup:

        this.println "Cleanup"
        executorService.shutdownNow()

        where:

        scenario                                                                                                   | sleep
        "faster than timeout, second (fast) stub has time to complete before timeout regardless of concurrency"    | 0
        "slower than timeout, second (fast) stub has time to complete only and only if it is running concurrently" | 5000

    }

    protected void println(String message) {
        super.println "${System.currentTimeSeconds()} [${Thread.currentThread().name}] ${message}"
    }
}
```
Output:
```
1513412620 [main] Start test with slow stub at 0ms
1513412620 [pool-1-thread-1] (1) Slow, sleeping for 0ms
1513412620 [pool-1-thread-2] (2) Fast
1513412621 [main] Cleanup
1513412621 [main] Start test with slow stub at 5000ms
1513412621 [pool-2-thread-1] (1) Slow, sleeping for 5000ms
1513412622 [main] Cleanup
1513412622 [pool-2-thread-2] (2) Fast

Condition not satisfied:

fastFuture.isDone()
|          |
|          false
java.util.concurrent.FutureTask@77f80c04


	at ConcurrentStubsSpec.#scenario(ConcurrentStubsSpec.groovy:53)

Picked up JAVA_TOOL_OPTIONS: "-XX:-UsePerfData" "-Duser.language=en" "-Duser.country=US" "-Duser.timezone=UTC" "-Dfile.encoding=UTF-8"

Process finished with exit code -1
```
- Execution 1 doesn't have strong concurrency expectations, the issue is not apparent
- Execution 2 has strong concurrency expectation, and fails because of the described issue


As stated by the OP, the root cause is the `synchronized` keyword around the whole stub execution (`- locked <0x675> (a org.spockframework.mock.runtime.MockController)` for _stub1_ and `waiting for pool-2-thread-1@1647 to release lock on <0x675> (a org.spockframework.mock.runtime.MockController)` for _stub2_):
```
"pool-2-thread-1@1647" prio=5 tid=0x13 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks pool-2-thread-2@1648
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	  at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:133)
	  at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	  at ConcurrentStubsSpec$__spock_feature_0_0_closure1$_closure3.doCall(ConcurrentStubsSpec.groovy:25)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	  at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	  at groovy.lang.Closure.call(Closure.java:414)
	  at org.spockframework.runtime.GroovyRuntimeUtil.invokeClosure(GroovyRuntimeUtil.java:204)
	  at org.spockframework.mock.response.CodeResponseGenerator.invokeClosure(CodeResponseGenerator.java:53)
	  at org.spockframework.mock.response.CodeResponseGenerator.doRespond(CodeResponseGenerator.java:36)
	  at org.spockframework.mock.response.SingleResponseGenerator.respond(SingleResponseGenerator.java:31)
	  at org.spockframework.mock.response.ResponseGeneratorChain.respond(ResponseGeneratorChain.java:45)
	  at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:76)
	  at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:46)
	  at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:41)
	  at org.spockframework.mock.runtime.MockController.handle(MockController.java:39)
	  - locked <0x675> (a org.spockframework.mock.runtime.MockController)
	  at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:74)
	  at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
	  at com.sun.proxy.$Proxy14.run(Unknown Source:-1)
	  at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:-1)
	  at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)
```
```
"pool-2-thread-2@1648" prio=5 tid=0x14 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for pool-2-thread-1@1647 to release lock on <0x675> (a org.spockframework.mock.runtime.MockController)
	  at org.spockframework.mock.runtime.MockController.handle(MockController.java:35)
	  at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:74)
	  at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
	  at com.sun.proxy.$Proxy14.run(Unknown Source:-1)
	  at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:-1)
	  at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by leonard84** [comment]
Yes concurrent access while blocking inside a response closure is a limitation of the `MockController`. However, both examples don't really need to use `Stub` since groovy lets you simply create a `Runnable` with a `{ ... } as Runnable`. Maybe this is just a shortened example and are you using maybe verification calls in your test. However, I don't think that this limitation will change anytime soon, but maybe we should add a note to the docs.

**Comment by AndreasTu** [comment]
PR  #1885 will fix this Issue.
