### ISSUE TITLE
Specification.noExceptionThrown() - improve UnallowedExceptionThrownError.getMessage()

### ISSUE THREAD

**Issue by toschder** [spockframework/spock#609]
# Issue description
Specification.noExceptionThrown() creates an UnallowedExceptionThrownError in case of an unexpected Exception.
UnallowedExceptionThrownError overrides getMessage() - resulting in a loss of the actual.getMessage() data. The getMessage() of the encapsulated exception (containing detailed information) will not be called.

Here´s a more detailed implementation, showing these details:

`public void noExceptionThrown() {
    Throwable thrown = getSpecificationContext().getThrownException();
    if (thrown == null) return;
    throw new UnallowedExceptionThrownError(null, thrown) {
      @Override
      public String getMessage() {
        if (unallowed == null) {
          return String.format("Expected no exception to be thrown, but got '%s:%s'", actual.getClass().getName(), actual.getMessage());
        }
        return String.format("Expected no exception of type '%s' to be thrown, but got it nevertheless",
            unallowed.getName());
      }
    };
  }
`

**Sample:**
`
ApacheSpec$1: Expected no exception to be thrown, but got 'org.openqa.selenium.WebDriverException:org.apache.http.conn.ConnectTimeoutException: Connect to rsp-dcomc-int2.mycompany.com:443 [rsp-dcomc-int2.mycompany.com/xxx.yy.zzz.147] failed: connect timed out
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'MUC-MAW-01', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-45-generic', java.version: '1.8.0_40'
Driver info: driver.version: HtmlUnitDriver'
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.connectSocket(HtmlUnitSSLConnectionSocketFactory.java:189)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:179)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1321)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1238)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:346)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:541)
at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:530)
at geb.Browser.go(Browser.groovy:508)
at geb.Browser.go(Browser.groovy:473)`

# How to reproduce 
> Please provide information how to reproduce this issue.
> Only applicable for bugs.

## Link to a gist or similar (optional)

# Additional Environment information
> Version of your build tool(if used), Java, Groovy, IDE, OS etc

## Java/JDK
1.8u40

## Groovy version
2.4.5-all

### Apache Maven
3.3.3

### Jenkins 
1.609

## Operating System
Linux, Windows

## IDE
Eclipse

### Apache Maven
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.0-groovy-2.4</version>
    </dependency>

**Comment by kriegaex** [comment]
We are also having problems diagnosing test failure root causes because `notThrown Exception` yields something like `org.spockframework.runtime.UnallowedExceptionThrownError: Expected no exception of type 'java.lang.Exception' to be thrown, but got it nevertheless` with a callstack showing where the error occurred, but not which exception incl. callstack had actually occurred instead of the expected one. Being used to comprehensive Spock error messages, power assertions etc., this one is really poor.

Can you please fix that problem and in the meantime maybe provide an idea concerning how to work around that limitation?

**Comment by leonard84** [comment]
@toschder, @kriegaex I don't quite understand the problem the offending exception is added as the cause of the `UnallowedExceptionThrownError` and is thus available including callstack.

```java
  def "no IOException allowed, IOException thrown"() {
    when:
    throw new IOException("foo")

    then:
    notThrown(IOException)
  }
```
```
Expected no exception of type 'java.io.IOException' to be thrown, but got it nevertheless

	at spock.lang.Specification.notThrown(Specification.java:106)
	at org.spockframework.smoke.condition.NegativeExceptionConditions.no IOException allowed, IOException thrown(NegativeExceptionConditions.groovy:53)
Caused by: java.io.IOException: foo
	at org.spockframework.smoke.condition.NegativeExceptionConditions.no IOException allowed, IOException thrown(NegativeExceptionConditions.groovy:50)
```

If the thrown exception is not assignable to the specified class it is rethrown as is.

**Comment by AndreasTu** [comment]
Closing old stale issue.
