### ISSUE TITLE
Unitils integration problem

### ISSUE THREAD

**Issue by linux-china** [spockframework/spock#62]
I have created a groovy class named MetricsBaseSpec, and I want it should be the base specification, and I add some annotation, such as SpringApplicationContext, code as following: 

```
@UnitilsSupport
@SpringApplicationContext(["/appContext-unit.xml"])
@DataSet(["/database/dataset/project.xml", "/database/dataset/metric.xml"])
public abstract class MetricsBaseSpec extends Specification {
}
```

then I create a new spec test groovy class named SpikeSpec, but I can't run the following feature: 

```
class SpikeSpec extends MetricsBaseSpec {
  @SpringBeanByType
  private ProjectRepository projectRepository;

  def "find project by id"() {
    Project project = 1.project
    expect:
    project.name == "demo"
  }
}
```

stack as following: 

```
java.lang.NullPointerException
    at org.spockframework.unitils.UnitilsInterceptor.interceptSetupMethod(UnitilsInterceptor.java:39)
    at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:28)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
    at org.spockframework.unitils.UnitilsInterceptor.interceptSetupMethod(UnitilsInterceptor.java:40)
    at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:28)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
    at org.spockframework.unitils.UnitilsInterceptor.interceptFeatureExecution(UnitilsInterceptor.java:70)
    at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:55)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

```

Is it the extend problem?

**Comment by AndreasTu** [comment]
Closing old stale issue.
