### ISSUE TITLE
Geb assertions broken by Spock 1.1 RC2

### ISSUE THREAD

**Issue by pkubowicz** [spockframework/spock#648]
Spock 1.1-groovy-2.4-rc-2 breaks assertions in geb-spock 0.13.1:
- if the assertion is not met, expected and actual values are not printed
- if the assertion is not met, screenshot is not made

To reproduce: write a Geb test with a failing `waitFor()`.

Expected message:
```
geb.waiting.WaitTimeoutException: condition did not pass in 5.0 seconds (failed with exception)
	at geb.waiting.Wait.waitFor(Wait.groovy:138)
	at geb.waiting.DefaultWaitingSupport.doWaitFor(DefaultWaitingSupport.groovy:51)
	at geb.waiting.DefaultWaitingSupport.waitFor(DefaultWaitingSupport.groovy:38)
	at geb.Page.waitFor(Page.groovy:506)
	at geb.Browser.methodMissing(Browser.groovy:206)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:56)
Caused by: Assertion failed: 

connectionColor() == "a"
|                 |
|                 false
"rgba(178, 186, 50, 1)"

	at geb.waiting.Wait.waitFor(Wait.groovy:127)
	... 6 more
```

Actual:
```
Condition not satisfied:

waitFor { connectionColor() == "a" }
|
geb.waiting.WaitTimeoutException: condition did not pass in 5.0 seconds

Caused by: geb.waiting.WaitTimeoutException: condition did not pass in 5.0 seconds
	at geb.waiting.Wait.waitFor(Wait.groovy:138)
	at geb.waiting.DefaultWaitingSupport.doWaitFor(DefaultWaitingSupport.groovy:51)
	at geb.waiting.DefaultWaitingSupport.waitFor(DefaultWaitingSupport.groovy:38)
	at geb.Page.waitFor(Page.groovy:506)
	at geb.Browser.methodMissing(Browser.groovy:206)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:56)
	... 1 more
```

**Comment by pkubowicz** [comment]
Works fine with Geb 1.0.
