### ISSUE TITLE
Scoped Beans cause error with spock-spring 1.1-groovy-2.4-rc-2

### ISSUE THREAD

**Issue by markward-schubert** [spockframework/spock#655]
I recently upgraded to spring boot 1.4.1, implying an upgrade to spring framwork 4.3.3.RELEASE.
A service-test, bootstrapping our Application with the following Annotations now fails with the Exception below:

Our Spec extends AbstractServiceSpec.

```
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class AbstractServiceSpec extends Specification {
[...]
}
```

**Exception:**

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:355) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.spockframework.spring.SpringMockTestExecutionListener.beforeTestMethod(SpringMockTestExecutionListener.java:49) ~[spock-spring-1.1-groovy-2.4-rc-2.jar:na]
    at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269) ~[spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.spockframework.spring.SpringTestContextManager.beforeTestMethod(SpringTestContextManager.java:54) [spock-spring-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.spring.SpringInterceptor.interceptSetupMethod(SpringInterceptor.java:45) [spock-spring-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:28) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:472) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runSetup(BaseSpecRunner.java:375) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runSetup(BaseSpecRunner.java:370) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:323) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:269) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:263) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.spockframework.runtime.Sputnik.run(Sputnik.java:63) [spock-core-1.1-groovy-2.4-rc-2.jar:na]
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117) [junit-rt.jar:na]
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42) [junit-rt.jar:na]
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262) [junit-rt.jar:na]
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84) [junit-rt.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
    at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.web.context.request.AbstractRequestAttributesScope.get(AbstractRequestAttributesScope.java:41) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    ... 41 common frames omitted
```

When I start the application "normally", meaning not from the Test, the Exception does not occur.
Do we have to adjust some configuration in the tests, or may this be some incompatibility between spock-spring 1.1 and spring-boot 1.4.1?

**Comment by mattbroekhuis** [comment]
have you had any luck yet? works fine on 1.4.0

I've found some threads with suggestions, but nothing seems to work. I too can run normally, it's just the tests that fail. I haven't tried to build a regular junit test yet to see if it's isolated to spock

**Comment by markward-schubert** [comment]
In the case of the very service, we are currently working on, it turned out, that we could go by removing the _spring-security-oauth2_ dependency. Thus the _OAuth2AutoConfiguration_ does not kick in and no bean named _oauth2ClientContext_ is created at all.

Of course I would not call this a "slolution" in the general sense of the word. 

I am far from deep into the logics of spock's _SpringMockTestExecutionListener_ but I understand, that the code, enabling to wire mocks into the application context under test, triggers code, within the spring framwork, which again triggers the creation of (all known?) beans. 
Amongst those beans is also the scoped _oauth2ClientContext_, which can not be retrieved by the current scope, because during bootstrapping the application there is no "request" scope. 

Maybe we should bring this issue also to the attention of the spring-security / spring-boot-autoconfiguration guys. I do not understand the details enought to evaluate, where we have an issue here, or even if it is just a combination issue.

**Comment by baronbaston** [comment]
I believe the fix for this issue is to change rows 46-48 in SpringMockTestExecutionListener from:

```Java
if(beanDefinition.isAbstract()){
    continue;
}
```

to

```Java
if(beanDefinition.isAbstract() || beanName.startsWith("scopedTarget.")){
    continue;
}
```

I tried making a pull request with the fix but didn't have permissions. Anyone know how to get permission?

**Comment by kiview** [comment]
This should normally work if you have forked the repository and create a pull request from your fork.

**Comment by baronbaston** [comment]
Thanks @kiview. Created a pull request: https://github.com/spockframework/spock/pull/670

**Comment by leonard84** [comment]
Closing since #670 has been merged
