### ISSUE TITLE
ByteBuddy >=1.6.0 causes NoSuchMethodError

### ISSUE THREAD

**Issue by Raniz85** [spockframework/spock#694]
I'm using Hibernate 5.2 (specifically [hibernate-entitymanager-5.2.7.FINAL](https://search.maven.org/#artifactdetails%7Corg.hibernate%7Chibernate-entitymanager%7C5.2.7.Final%7Cjar)) which depends on bytebuddy-1.6.0, causing Spock to pick it up and subsequently throw:

```
java.lang.NoSuchMethodError: net.bytebuddy.implementation.MethodDelegation.appendParameterBinder(Lnet/bytebuddy/implementation/bind/annotation/TargetMethodAnnotationDrivenBinder$ParameterBinder;)Lnet/bytebuddy/implementation/MethodDelegation;

	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:115)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:63)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:83)
```

This is easily worked around by setting the system property `org.spockframework.mock.ignoreByteBuddy` to `false`, but I think the optional dependency on Byte Buddy should be updated. 

1.6.7 is the latest version available in Maven Central as this moment.

**Comment by szpak** [comment]
It should be fixed by #682. Already in master will be available in the next RC version.

**Comment by szpak** [comment]
Btw, #687 is also related.

**Comment by facboy** [comment]
Perhaps spock should shade byte-buddy?

**Comment by szpak** [comment]
@facboy We had similar [discussion](https://github.com/mockito/mockito/issues/943) in the Mockito team and we will rather not be shading BB in the nearest future. There is a chance that further BB version will be more backward compatible.

**Comment by facboy** [comment]
Yes, but in the meantime it makes life difficult for some Spock users. Maybe there could be a separate shaded artifact so users have a choice.

**Comment by dilipkrish** [comment]
@szpak any idea when the next rc is planned to be released?

**Comment by leonard84** [comment]
@Raniz85 1.1 is released using ByteBuddy 1.6.5 does this fix your issue?

**Comment by Raniz85** [comment]
Yes, that should do it

**Comment by dilipkrish** [comment]
\o/
