### ISSUE TITLE
Spock 1.1-rc-X breaks nebula-test with IllegalStateException: can not found call #0 on stack. Invalid call of record method?

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#714]
# Issue description
nebula-test seems to be broken with Spock 1.1. The following exception is thrown when `runTasksWithFailure()` method is used:

```
java.lang.IllegalStateException: can not found call #0 on stack. Invalid call of record method?

	at nebula.test.IntegrationSpec.runTasksWithFailure(IntegrationSpec.groovy:282)
	at my.code.FooSpec.should pass on failure(FooSpec.groovy:24)
```

which internally does:
```
    protected ExecutionResult runTasksWithFailure(String... tasks) {
        ExecutionResult result = runTasks(tasks)
        assert result.failure
        result
    }
```

# How to reproduce

Minimal test to reproduce the issue:

```
class ReproducingSpec extends IntegrationSpec {

    def "should no fail test on runTasksWithFailure()"() {
        when:
            ExecutionResult result = runTasksWithFailure("wrongTasks")
        then:
            result.failure.message.contains('wrongTasks')
    }
}
```

# Versions

Tested with Spock 1.1-rc-1 to 1.1-rc-4 with:
 - Nebula 5.0.0 and 5.1.3 with Gradle 3.4 (Groovy 2.4.7)
 - Nebula 4.4.3 with Gradle 2.13 (Groovy 2.4.4)

# Additional information

If checked in debug it seems that there recording hasn't been started (no `startedRecordings` in `ValueRecorder`) when in `record` method is invoked.

@Fuud Can it be related to your changes in better exceptions/errors rendering?

# Full stacktrace

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:174)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:406)
	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:324)
	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:472)
	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288)
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278)
	at org.spockframework.runtime.ParameterizedSpecRunner.runIterations(ParameterizedSpecRunner.java:139)
	at org.spockframework.runtime.ParameterizedSpecRunner.runParameterizedFeature(ParameterizedSpecRunner.java:41)
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:262)
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238)
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: can not found call #0 on stack. Invalid call of record method?
	at org.spockframework.runtime.ValueRecorder.record(ValueRecorder.java:58)
	at nebula.test.IntegrationSpec.runTasksWithFailure(IntegrationSpec.groovy:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at my.code.FooSpec.should pass on failure(FooSpec.groovy:24)
	... 39 more
```

**Comment by leonard84** [comment]
@szpak do you have a [SSCCE ](http://sscce.org/)? The provided example is too limited. From a cursory look: it seems that nebula-test itself depends on spock and thus would need a new build based on spock 1.1 to make it compatible.

**Comment by DanielThomas** [comment]
@szpak I'm on the Nebula team @ Netflix; @twicksell gave us a heads up about the problem you were having. 

We'll be rolling nebula-test 6.0.0 that bundles 1.1-rc-4. Let us know if that doesn't work for you over at https://github.com/nebula-plugins/nebula-test. Unfortunately Travis CI isn't running jobs right now due to a DB issue over there, once this completes, give it a try:

https://travis-ci.org/nebula-plugins/nebula-test/builds/216493752
