### ISSUE TITLE
document how to create spy with instantiated object

### ISSUE THREAD

**Issue by snimavat** [spockframework/spock#749]
The docs says

> You may also create a spy from an instantiated object. This may be useful in cases where you do not have full control over the instatiation of types you are interested in spying. (For example when testing within a Dependency Injection framework such as Spring or Guice.)

but there is no example of it. 

Trying
```

Service service = new Service()
Service spy = Spy(service)
```

results in error

**Comment by leonard84** [comment]
@snimavat what version of spock are you using and what is the error?

**Comment by tommyb82** [comment]
Also interested in this - trying to use the spy API to listen in on calls to my classes `LOG` field, but it doesn't seem to recognise the interactions.  I am not seeing any errors, but none of the interactions are picked up:

    Logger log = Logger.getLogger(My.class);
    def logSpy = Spy(log)

    LOG.info(...)
    1 * logSpy.info(_ as String)

etc.. results in 'too few invocations..'

is that a valid use case? Should it work?  I am using the latest version: `1.1-groovy-2.4`

**Comment by snimavat** [comment]
@leonard84 its spockframework:spock-core:1.0-groovy-2.4

**Comment by tommyb82** [comment]
@snimavat - I would expect it to throw an exception pre 1.1 - it's a new feature in that version (supposedly)

**Comment by leonard84** [comment]
@snimavat it is a new feature of 1.1 so it won't work in versions prior to that.
@tommyb82 it won't modifiy the existing object but wrap a spy around it, so the way you are using it won't work. You need to use the return value from `Spy` instead of the original object. Furthermore, the way loggers are created are not really helpful for that.

```
given:
def logSpy = Spy(Logger.getLogger(My.class))
when:
logSpy.info(...)
then:
1 * logSpy.info(_ as String)
```

**Comment by tommyb82** [comment]
Thanks @leonard84, that makes a lot of sense but perhaps it could be a little clearer in the docs.  I had assumed a kind of AOP model where methods in the object being spied upon would be 'wrapped' by the spy.

**Comment by leonard84** [comment]
@tommyb82 they are wrapped, but you need to use the wrapper. It is the same with spring only the wrapper gets injected, only the intricacies are hidden from you, which is not possible here.

**Comment by haridsv** [comment]
@leonard84 When I try to create a spy of a script object, something like this:

```
        def shell = new GroovyShell()
        Script scr = shell.parse('')
        scr = Spy(scr)
```

I get the below CNFE. It looks like it is trying to instantiate a new script object, shouldn't it just wrap the one I passed in?

```
 java.lang.IllegalArgumentException: Could not create type
         at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
         at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
         at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
         at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
         at org.spockframework.mock.runtime.ByteBuddyMockFactory.createMock(ByteBuddyMockFactory.java:41)
         at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:42)
         at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:58)
         at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:38)
         at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:42)
         at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:46)
         at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:294)
         at org.spockframework.lang.SpecInternals.SpyImpl(SpecInternals.java:183)
         at buildopsSpec.setup(buildopsSpec.groovy:26)
 Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
         at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:608)
         at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:235)
         at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:111)
         at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:232)
         at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
         at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
         at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5623)
         at org.spockframework.mock.runtime.ByteBuddyMockFactory$1.call(ByteBuddyMockFactory.java:55)
         at org.spockframework.mock.runtime.ByteBuddyMockFactory$1.call(ByteBuddyMockFactory.java:43)
         at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
         ... 12 more
 Caused by: java.lang.NoClassDefFoundError: Script1
         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
         at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:604)
         ... 21 more
 Caused by: java.lang.ClassNotFoundException: Script1
         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
         ... 23 more
```

I am using version 1.3 with Groovy 2.5.

**Comment by haridsv** [comment]
I encountered the above while I was trying to reproduce the issue #822 using a simple script. I was trying to create a Spy on top of the script object returned by [PipelineTestHelper.loadScript](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/fe5223c3dbe40148979a52f7abb3bc3c863551cf/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L321
) from JenkinsPipelineUnit and got this exception:

```
 java.lang.IllegalArgumentException: source and target are not compatible.
         at org.spockframework.util.ReflectionUtil.deepCopyFields(ReflectionUtil.java:262)
         at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:62)
         at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:38)
         at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:42)
         at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:46)
         at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:294)
         at org.spockframework.lang.SpecInternals.SpyImpl(SpecInternals.java:183)
         at buildopsSpec.setup(buildopsSpec.groovy:27)
```

In my case, `loadScript` returns a script object of a type that extends [CpsScript](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java), which in turns extends groovy.lang.Script, so I thought of reproducing using a plan script and that got me the error reported in the previous comment.
