### ISSUE TITLE
documentation error reporting 

### ISSUE THREAD

**Issue by chanwookpark** [spockframework/spock#766]
Hi~
Sample code in Reference has some error.

[Multi variable data pipe chapter](http://spockframework.org/spock/docs/1.1/all_in_one.html#_multi_variable_data_pipes) is describing to connect sql.

```groovy 
@Shared sql = Sql.newInstance("jdbc:h2:mem:", "org.h2.Driver")
...
```

But this code throw exception.

```
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:mem". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-182]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.get(DbException.java:179)
at org.h2.message.DbException.get(DbException.java:155)
at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:398)
at org.h2.engine.Engine.openSession(Engine.java:45)
at org.h2.engine.Engine.openSession(Engine.java:167)
at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
at org.h2.engine.Engine.createSession(Engine.java:128)
at org.h2.engine.Engine.createSession(Engine.java:26)
at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
at org.h2.Driver.connect(Driver.java:72)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:270)
at groovy.sql.Sql.newInstance(Sql.java:281)
at groovy.sql.Sql.newInstance(Sql.java:490)
at spock.MathSpecification.$spock_initializeSharedFields(MathSpecification.groovy:64)
```

According to H2 guide db connection url is something wrong. 
http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90011 

- current spock code: "jdbc:h2:mem:"
- h2 guide : "jdbc:h2:~/mem" 

But not always thrown exception, update sample code for that not confuse.

My environments is JDK 8, IntelliJ, gradle and spock-core:1.1-groovy-2.4.

thanks.

**Comment by leonard84** [comment]
If you look at http://www.h2database.com/html/features.html#database_url the following is listed here:

* In-memory (private) | `jdbc:h2:mem:`

The docs you are referencing are also unit tested https://github.com/spockframework/spock/blob/fab978b2461b6eb89d1abd9dd2e14938d1ee35c5/spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy#L12 and working without issue.

Are you sure that your jdbc-url ends with `:`?

**Comment by chanwookpark** [comment]
Hi, leonard84.
you are catch my missing!
I'm not containing : 

` jdbc:h2:mem:` is do it without error !!

Thanks for your help!
