### ISSUE TITLE
Unable to spy existing object if it does not have non argument contructor

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#769]
# Issue description
Spock fails to create a spy on a real object if it doesn't have a non argument constructor.

```
org.spockframework.mock.CannotCreateMockException: Cannot create mock for class info.solidsoft.gradle.cdeliveryboy.FooSpec$Foonull

	at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:38)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:133)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:65)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:51)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:296)
	at org.spockframework.lang.SpecInternals.SpyImpl(SpecInternals.java:185)
	at info.solidsoft.gradle.cdeliveryboy.FooSpec.should create spy for real object which does not have non argument constructor(FooSpec.groovy:21)
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: info.solidsoft.gradle.cdeliveryboy.FooSpec$Foo$SpockMock$astcHGKS()
	at org.spockframework.mock.runtime.MockInstantiator.instantiate(MockInstantiator.java:33)
	... 9 more
```

Spock seems to not use Objenesis to create an instance of the wrapping object. If manually switched to `useObjenesis` (in debugger as `Spy(obj)` does not provide that variant) it works fine. However, for spies probably a constructor should not be called in any case (while working with real objects).

# How to reproduce

```
    def "should create spy for real object which does not have non argument constructor"() {
        expect:
            Spy(new Foo(4))
    }

    static class Foo {
        Foo(int v) {
        }
    }
```

# Additional Environment information
Spock 1.1-groovy-2.4, Byte Buddy 1.7.5, Objenesis 2.6, Groovy 2.4.10, Java 1.8.0_144

**Comment by leonard84** [comment]
> However, for spies probably a constructor should not be called in any case (while working with real objects).

To clarify, spies need to be instantiated using their constructor otherwise the internal state is compromised. For the newly added feature of spying on existing instances this was already done beforehand (by the user or a framework), so the usage of `useObjenesis` is OK here.

**Comment by szpak** [comment]
That's while I precised "while working with real objects".
