### ISSUE TITLE
GroovySpy incompatible with statically compiled classes (spock-core 1.0-groovy-2.4)

### ISSUE THREAD

**Issue by shils** [spockframework/spock#81]
Testing for a static method call does not seem to work when the code calling the static method is statically compiled. Example:

```
import groovy.transform.CompileStatic
import spock.lang.Specification

class SpyStaticMethodTest extends Specification {

  def sorter = new Sorter()

  def testMockStaticMethod(){
    given:
    GroovySpy(global: true, Collections)

    when: 'method being called is not statically compiled'
    sorter.sort([1,2,3])

    then: 'Collections.sort(list) should be called'
    1 * Collections.sort(_)

    when: 'method being called is statically compiled'
    sorter.sortSTC([1,2,3])

    then: 'Collections.sort(list) should be called' // Too few invocations, and no unmatched invocations
    1 * Collections.sort(_)
  }

  static class Sorter {
    void sort(List<Integer> list) {
      Collections.sort(list)
    }

    @CompileStatic
    void sortSTC(List<Integer> list) {
      Collections.sort(list)
    }
  }
}
```

The test above fails with the following message:
```
Too few invocations for:

1 * Collections.sort(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

None

	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:78)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:76)
	at me.anyti.SpyStaticMethodTest.testMockStaticMethod(SpockStaticSpyTest.groovy:19)
```

Is this expected behavior (for the same reason global mocks don't work with java classes)?

**Comment by leonard84** [comment]
As you correctly guessed it is the expected behavior, global mocking is not possible with `GroovySpy` for static compiled code. I've included the bytecode to show the difference.

Byte code from sort
```
LINENUMBER 29 L1
    ALOAD 2
    LDC 0
    AALOAD
    LDC Ljava/util/Collections;.class
    ALOAD 1
    INVOKEINTERFACE org/codehaus/groovy/runtime/callsite/CallSite.call (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    POP
```
Here you can see that it uses Groovy's MOP to invoke the `Collections.sort` method.

Byte code from sortSTC
```
LINENUMBER 34 L0
    ALOAD 1
    INVOKESTATIC java/util/Collections.sort (Ljava/util/List;)V
    ACONST_NULL
    POP
```
And in the static version it is just a direct static method call, without any Groovy MOP.
