### ISSUE TITLE
Commit 8c851c6 introduces initializationError

### ISSUE THREAD

**Issue by henrik242** [spockframework/spock#813]
Commit 8c851c6 (`Add @SpringBean and @SpringSpy inspired by @MockBean..` #796 ) introduces a  java.lang.annotation.IncompleteAnnotationException in my tests.   It hasn't been fixed in later commits (the latest I tried was commit b01eb41 )

```
java.lang.annotation.IncompleteAnnotationException: org.spockframework.runtime.model.FieldMetadata missing element initializer
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy13.initializer(Unknown Source)
	at org.spockframework.runtime.SpecInfoBuilder.buildFields(SpecInfoBuilder.java:103)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:64)
	at org.spockframework.runtime.SpecInfoBuilder.buildSuperSpec(SpecInfoBuilder.java:75)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:62)
	at org.spockframework.runtime.SpecInfoBuilder.buildSuperSpec(SpecInfoBuilder.java:75)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:62)
	at org.spockframework.runtime.SpecInfoBuilder.buildSuperSpec(SpecInfoBuilder.java:75)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:62)
	at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:49)
	at org.spockframework.runtime.Sputnik.getSpec(Sputnik.java:82)
	at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:90)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:61)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by leonard84** [comment]
This relates #801 could you provide more information about your setup, do you also have a grails project?

**Comment by henrik242** [comment]
This is a `geb.spock.GebReportingSpec` test.  I don't use grails.

**Comment by leonard84** [comment]
@henrik242 were you using pre-compiled tests, and did just change the spock version at runtime?

**Comment by henrik242** [comment]
I'm not using precompiled tests.  And I changed the spock version in gradle's `testCompile` block.

**Comment by leonard84** [comment]
@henrik242 have you tried if it is fixed with the recent change?

**Comment by henrik242** [comment]
@leonard84 I tried with commit b0f30cf, and it works flawlessly.  Thanks!
