### ISSUE TITLE
Spock tries to mock return values from Stub() block

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#82]
I am stubbing a Spring Data repository:

```
BookingPromoRepository promos = Stub() {
    findByCode('valid') >> new PercentOffMinimumItems(5, 5.0)
}
```

where `PercentOffMinimumItems extends BookingPromo` is a concrete class for which I want to return an ordinary instance from the repository stub. However, I get the following exception:

```
org.spockframework.mock.CannotCreateMockException: Cannot create mock for class com.artsquare.studio.domain.digitization.BookingPromo. Mocking of non-interface types requires the CGLIB library. Please put cglib-nodep-2.2 or higher on the class path.
    at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:52)
    at org.spockframework.mock.runtime.GroovyMockFactory.create(GroovyMockFactory.java:66)
    at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
    at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
    at org.spockframework.mock.EmptyOrDummyResponse.createDummy(EmptyOrDummyResponse.java:123)
    at org.spockframework.mock.EmptyOrDummyResponse.respond(EmptyOrDummyResponse.java:92)
    at org.spockframework.mock.runtime.MockController.handle(MockController.java:49)
    at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:72)
    at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:28)
    at com.artsquare.studio.policy.booking.BookingCalculatorImpl.calculatePrice(BookingCalculatorImpl.groovy:37)
    at com.artsquare.studio.policy.booking.BookingCalculatorImplTest.ignores missing or invalid promo codes(BookingCalculatorImplTest.groovy:33)
```

Wrapping the `new` in a closure has no effect on this behavior.

I'm running `1.0-groovy-2.4` with Groovy 2.4.3.

**Comment by pniederw** [comment]
See the error message:

> Mocking of non-interface types requires the CGLIB library. Please put cglib-nodep-2.2 or higher on the class path.

**Comment by chrylis** [comment]
Please read the exception message. `BookingPromoRepository`, the type being mocked, is an interface. Spock is trying to mock *the return value*.

**Comment by kurron** [comment]
I am seeing this as well with Groovy 2.4.7.

**Comment by pniederw** [comment]
A `Stub` will try to return an object of the declared return type when no specified interaction matches. Since it doesn't know how to create an instance of `Instant` (which has no zero-argument constructor), it tries to return another `Stub`, which fails because `Instant` is a final class.

In other words, it looks like the code under test calls a method  other than `checkTheTimeWithFallback` on the stub. Same is probably true in @chrylis' case.

In comparison, a `Mock` will return `null` for an unexpected invocation. If you made the Mock/Stub strict (see docs for details), it would show the unexpected invocation.

**Comment by kurron** [comment]
@pniederw You are 100% correct.  The subject under test was, in fact, calling two methods and I had only trained the stub for 1.  The working test now looks like this:

```
    def 'exercise currentTime happy path'() {
        given: 'a subject under test'
        def stub = Stub( TimePort ) {
            checkTheTimeWithFallback() >> Instant.now()
            checkTheTimeWithoutFallback() >> Instant.now()
        }

        def sut = new TemporalAcquisitionService( stub )

        when: 'we call currentTime'
        def results = sut.currentTime()

        then: 'we get expected results'
        Instant.now().epochSecond == results.epochSecond
    }
```
Thanks you so much for your assistance.
