### ISSUE TITLE
Getting Initialization error when using gradle test with @RunWith(ProgressSuite.class) in a test suite with spock-core dependency

### ISSUE THREAD

**Issue by adhithyasrinivasan** [spockframework/spock#837]
Exception in thread "org.spockframework.runtime.RunContext.stop()" java.lang.AbstractMethodError: org.imaginea.jenkins.testinprogress.spock.SpockTestInProgressExtension.stop(
        at org.spockframework.runtime.GlobalExtensionRegistry.stopGlobalExtensions(GlobalExtensionRegistry.java:111)
        at org.spockframework.runtime.RunContext.stop(RunContext.java:67)
        at org.spockframework.runtime.RunContext.access$000(RunContext.java:30)
        at org.spockframework.runtime.RunContext$2.run(RunContext.java:159)

**build.gradle**
testCompile 'org.spockframework:spock-core:1.1-groovy-2.4'

**HappyPathTestSuite.java**
import org.jenkinsci.testinprogress.runner.ProgressSuite;
import org.junit.runner.RunWith;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(ProgressSuite.class)
@SuiteClasses({CustomerFlowSpec.class})
public class HappyPathTestSuite {

}

**Comment by leonard84** [comment]
Since Spock is a uses a JUnit runner itself and you can only have one runner for a test this won't work.
