### ISSUE TITLE
MockFactory should use classloader of the mock type to create instance rather than the classloader of the Specification

### ISSUE THREAD

**Issue by noproxy** [spockframework/spock#960]
# Issue description

Currently, when MockFactory(GroovyMockFactory/ JavaMockFactory) try to create mock instance, it will use the `specification.getClass().getClassLoader()`.  

This limits that the mock type can only be loaded by the same classloader as specification. In my project, I should write some classes as test input/data to test my business code. They are the data of the test, and not my test code, so I want to generate and load it in my test code. At now, spock does not support mock them.

# How to reproduce

Just mock any class loaded by custom classloader will produce exception.

```groovy
    def "spock should support mock a type loaded by custom classloader"() {
        given:
        GroovyClassLoader loader = new GroovyClassLoader()
        Class clazz = loader.parseClass("""
class DemoClazz {
    public void test(){
    }
}
""")
        when:
        def object = GroovyMock(clazz)

        then:
        noExceptionThrown()
    }

```

And will failed with:

```
Expected no exception to be thrown, but got 'java.lang.IllegalArgumentException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at di.OptionalCallerTest.spock not support mock a type loaded by custom classloader(OptionalCallerTest.groovy:69)
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:350)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:361)
	at org.spockframework.mock.runtime.ByteBuddyMockFactory.createMock(ByteBuddyMockFactory.java:41)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:42)
	at org.spockframework.mock.runtime.GroovyMockFactory.create(GroovyMockFactory.java:75)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:42)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:46)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:294)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:284)
	at org.spockframework.lang.SpecInternals.GroovyMockImpl(SpecInternals.java:203)
	at di.OptionalCallerTest.spock not support mock a type loaded by custom classloader(OptionalCallerTest.groovy:66)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:593)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:220)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:96)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:217)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:128)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:85)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5608)
	at org.spockframework.mock.runtime.ByteBuddyMockFactory$1.call(ByteBuddyMockFactory.java:55)
	at org.spockframework.mock.runtime.ByteBuddyMockFactory$1.call(ByteBuddyMockFactory.java:43)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: DemoClazz
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:589)
	... 21 more
Caused by: java.lang.ClassNotFoundException: DemoClazz
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

```

## Link to a gist or similar (optional)

# Additional Environment information

Gradle 5.0, , Groovy

## Java/JDK
java 8.0_u121

## Groovy version

groovy 2.5.4

### Gradle
gradle 5.0

## Operating System

Mac

## IDE

IntelliJ IDEA 2018.3

### Gradle/Grails
```
    testImplementation 'junit:junit:4.12'
    testImplementation 'net.bytebuddy:byte-buddy:1.9.2'
    testImplementation 'org.objenesis:objenesis:3.0.1'
    testImplementation("org.spockframework:spock-core:1.2-groovy-2.5") {
        exclude group: "org.codehaus.groovy", module: "groovy-all"
    }
```

**Comment by noproxy** [comment]
I find I can mock type loaded by custom classloader in this way:

```groovy
  given:
        ClassLoader classloader = new GroovyClassLoader(ClassLoader.getSystemClassLoader())
        Class<?> featureClazz = classloader.parseClass(...)
        def util = new MockUtil()
        def feature = util.createDetachedMock("mockForFeature", featureClazz, 
                MockNature.MOCK, MockImplementation.JAVA, Collections.emptyMap(), classloader)
        util.attachMock(feature, this)
```

Is this the correct way to use `detachMock`? If so, this issue can be close.

**Comment by leonard84** [comment]
Why do you need to combine mocking with dynamic classes?

**Comment by noproxy** [comment]
> Why do you need to combine mocking with dynamic classes?

I am writing tests for runtime annotations processor. There are some dynamic classes that work as input data for tests. And the expected results are the invoking of the annotated methods in the dynamic classes.

**Comment by noproxy** [comment]
> That is the low level way to create a mock, normally you should use `DetachedMockFactory`.

Thanks! I think this issue can be close because existing api can cover my situation.
